"""BESS-TS6-005: derived-set staleness and regeneration.

Proves the derived-data lifecycle: a new revision of a source set marks every
derived set produced from it stale (Layer 1, reusing the generic
`validation_dependencies` + `evaluate_variant_staleness` mechanism with
`owner_type = 'time_series_set'`), a stale derived set can be regenerated by
re-executing its stored recipe against current input revisions (a new revision
of the same set, never a new set), history stays immutable, and a variant
bound to a stale derived set is blocked through the existing TS-3 fail-closed
gates.
"""

import unittest
from datetime import datetime, timedelta

from app.persistence import AnalystStore
from app.time_series_catalog import (
    CatalogImportRequest,
    CatalogSignalMappingRequest,
    CatalogValueEdit,
    prepare_time_series_catalog_import,
)


def demand_price_import_request(*, version_label="v1"):
    return CatalogImportRequest(
        set_name="Demand and price base",
        version_label=version_label,
        data_kind="real",
        timezone="America/Santiago",
        timestamp_column="period_start",
        duration_hours_column="hours",
        signal_mappings=[
            CatalogSignalMappingRequest(source_column="demand", signal_key="load_demand_mw"),
            CatalogSignalMappingRequest(
                source_column="price", signal_key="import_price_usd_per_mwh"
            ),
        ],
    )


def demand_price_rows(start, count):
    rows = []
    for hour in range(count):
        instant = start + timedelta(hours=hour)
        rows.append(
            {
                "period_start": instant.isoformat(),
                "hours": "1.0",
                "demand": str(100.0 + hour),
                "price": str(50.0 + hour),
            }
        )
    return rows


class DerivedScaleFixtureMixin:
    def setUp(self):
        self.store = AnalystStore("sqlite:///:memory:")
        self.addCleanup(self.store.close)
        self.project = self.store.create_project(name="TS6-005 project")
        self.scenario = self.store.create_scenario(
            project_id=self.project["id"], name="TS6-005 scenario"
        )
        prepared = prepare_time_series_catalog_import(
            rows=demand_price_rows(datetime(2026, 1, 1), 3),
            request=demand_price_import_request(),
        )
        self.source_set = self.store.import_time_series_catalog_set(
            scenario_id=self.scenario["id"],
            source={
                "id": "csv_source_1",
                "original_filename": "demand_price.csv",
                "media_type": "text/csv",
                "checksum": "sha256:test",
            },
            prepared_import=prepared,
        )
        self.derived_set = self.store.apply_time_series_transformation(
            project_id=self.project["id"],
            time_series_set_id=self.source_set["id"],
            transformation_type="scale_signal",
            raw_parameters={"signal_key": "load_demand_mw", "scale_factor": 2.0},
        )

    def _edit_source(self, *, value_text="999.0"):
        self.store.edit_time_series_set_values(
            project_id=self.project["id"],
            time_series_set_id=self.source_set["id"],
            edits=[
                CatalogValueEdit(
                    period_index=0, signal_key="load_demand_mw", value_text=value_text
                )
            ],
        )


class DerivedSetStalenessTests(DerivedScaleFixtureMixin, unittest.TestCase):
    def test_fresh_derived_set_is_not_stale(self):
        staleness = self.store.evaluate_time_series_set_staleness(
            self.project["id"], self.derived_set["id"]
        )

        self.assertTrue(staleness["validated"])
        self.assertFalse(staleness["stale"])
        self.assertEqual(staleness["reasons"], [])

    def test_new_source_revision_marks_the_derived_set_stale(self):
        self._edit_source()

        staleness = self.store.evaluate_time_series_set_staleness(
            self.project["id"], self.derived_set["id"]
        )

        self.assertTrue(staleness["stale"])
        self.assertEqual(
            [reason["dependency_type"] for reason in staleness["reasons"]],
            ["time_series_set"],
        )
        self.assertEqual(
            staleness["reasons"][0]["dependency_id"], str(self.source_set["id"])
        )

    def test_non_derived_sets_are_never_stale(self):
        self._edit_source()

        staleness = self.store.evaluate_time_series_set_staleness(
            self.project["id"], self.source_set["id"]
        )

        self.assertFalse(staleness["validated"])
        self.assertFalse(staleness["stale"])

    def test_catalog_list_flags_stale_derived_sets(self):
        self._edit_source()

        sets_by_id = {
            entry["id"]: entry
            for entry in self.store.list_time_series_sets(self.project["id"])
        }

        self.assertTrue(sets_by_id[self.derived_set["id"]]["stale"])
        self.assertFalse(sets_by_id[self.source_set["id"]]["stale"])

    def test_catalog_list_does_not_flag_fresh_derived_sets(self):
        sets_by_id = {
            entry["id"]: entry
            for entry in self.store.list_time_series_sets(self.project["id"])
        }

        self.assertFalse(sets_by_id[self.derived_set["id"]]["stale"])

    def test_bumping_the_implementation_version_marks_derived_outputs_stale(self):
        import dataclasses
        from unittest import mock

        from app import transformations

        bumped = dataclasses.replace(
            transformations.TRANSFORMATION_REGISTRY["scale_signal"],
            implementation_version=2,
        )
        patched_registry = {
            **transformations.TRANSFORMATION_REGISTRY,
            "scale_signal": bumped,
        }
        with mock.patch.object(
            transformations, "TRANSFORMATION_REGISTRY", patched_registry
        ):
            staleness = self.store.evaluate_time_series_set_staleness(
                self.project["id"], self.derived_set["id"]
            )

        self.assertTrue(staleness["stale"])
        self.assertEqual(
            [reason["dependency_type"] for reason in staleness["reasons"]],
            ["transformation_implementation"],
        )


class RegenerateDerivedSetTests(DerivedScaleFixtureMixin, unittest.TestCase):
    def test_regenerating_a_stale_set_re_executes_the_recipe_on_current_inputs(self):
        self._edit_source(value_text="200.0")

        regenerated = self.store.regenerate_derived_time_series_set(
            project_id=self.project["id"],
            time_series_set_id=self.derived_set["id"],
            created_by="analyst@example.com",
        )

        self.assertEqual(regenerated["id"], self.derived_set["id"])
        self.assertEqual(regenerated["revision_number"], 2)
        self.assertNotEqual(regenerated["content_hash"], self.derived_set["content_hash"])
        values_by_key = {
            (value["period_index"], value["signal_key"]): value["value_numeric"]
            for value in regenerated["values"]
        }
        self.assertAlmostEqual(values_by_key[(0, "load_demand_mw")], 400.0)
        self.assertAlmostEqual(values_by_key[(0, "import_price_usd_per_mwh")], 50.0)

    def test_regeneration_updates_lineage_and_clears_staleness(self):
        self._edit_source(value_text="200.0")
        current_source = self.store.get_time_series_set(
            self.project["id"], self.source_set["id"]
        )

        regenerated = self.store.regenerate_derived_time_series_set(
            project_id=self.project["id"],
            time_series_set_id=self.derived_set["id"],
        )

        transformation = regenerated["revision_metadata"]["transformation"]
        self.assertEqual(transformation["type"], "scale_signal")
        self.assertEqual(
            transformation["parameters"],
            {"signal_key": "load_demand_mw", "scale_factor": 2.0},
        )
        lineage_input = transformation["inputs"][0]
        self.assertEqual(lineage_input["time_series_set_id"], self.source_set["id"])
        self.assertEqual(lineage_input["revision_number"], current_source["revision_number"])
        self.assertEqual(lineage_input["content_hash"], current_source["content_hash"])
        staleness = self.store.evaluate_time_series_set_staleness(
            self.project["id"], self.derived_set["id"]
        )
        self.assertFalse(staleness["stale"])

    def test_regenerating_a_fresh_set_converges_without_a_new_revision(self):
        regenerated = self.store.regenerate_derived_time_series_set(
            project_id=self.project["id"],
            time_series_set_id=self.derived_set["id"],
        )

        self.assertEqual(regenerated["revision_number"], 1)
        self.assertEqual(regenerated["content_hash"], self.derived_set["content_hash"])
        revisions = self.store.list_time_series_set_revisions(
            self.project["id"], self.derived_set["id"]
        )
        self.assertEqual(len(revisions), 1)

    def test_regeneration_preserves_the_previous_revision_untouched(self):
        self._edit_source(value_text="200.0")

        self.store.regenerate_derived_time_series_set(
            project_id=self.project["id"],
            time_series_set_id=self.derived_set["id"],
        )

        revisions = self.store.list_time_series_set_revisions(
            self.project["id"], self.derived_set["id"]
        )
        by_number = {revision["revision_number"]: revision for revision in revisions}
        self.assertEqual(sorted(by_number), [1, 2])
        self.assertEqual(
            by_number[1]["content_hash"], self.derived_set["content_hash"]
        )
        self.assertEqual(by_number[2]["superseded_revision_number"], 1)

    def test_regenerating_a_non_derived_set_is_rejected(self):
        from app.transformations import TransformationError

        with self.assertRaises(TransformationError):
            self.store.regenerate_derived_time_series_set(
                project_id=self.project["id"],
                time_series_set_id=self.source_set["id"],
            )


class RegenerateCombinedSetTests(unittest.TestCase):
    """Regeneration also covers the multi-input combine_signals recipe."""

    def setUp(self):
        self.store = AnalystStore("sqlite:///:memory:")
        self.addCleanup(self.store.close)
        self.project = self.store.create_project(name="TS6-005 combine project")
        self.scenario = self.store.create_scenario(
            project_id=self.project["id"], name="TS6-005 combine scenario"
        )
        price_prepared = prepare_time_series_catalog_import(
            rows=[
                {
                    "period_start": (datetime(2026, 1, 1) + timedelta(hours=hour)).isoformat(),
                    "hours": "1.0",
                    "price": str(50.0 + hour),
                }
                for hour in range(3)
            ],
            request=CatalogImportRequest(
                set_name="Price only",
                version_label="v1",
                data_kind="real",
                timezone="America/Santiago",
                timestamp_column="period_start",
                duration_hours_column="hours",
                signal_mappings=[
                    CatalogSignalMappingRequest(
                        source_column="price", signal_key="import_price_usd_per_mwh"
                    ),
                ],
            ),
        )
        self.price_set = self.store.import_time_series_catalog_set(
            scenario_id=self.scenario["id"],
            source={
                "id": "csv_source_price",
                "original_filename": "price.csv",
                "media_type": "text/csv",
                "checksum": "sha256:price",
            },
            prepared_import=price_prepared,
        )
        demand_prepared = prepare_time_series_catalog_import(
            rows=[
                {
                    "period_start": (datetime(2026, 1, 1) + timedelta(hours=hour)).isoformat(),
                    "hours": "1.0",
                    "demand": str(100.0 + hour),
                }
                for hour in range(3)
            ],
            request=CatalogImportRequest(
                set_name="Demand only",
                version_label="v1",
                data_kind="real",
                timezone="America/Santiago",
                timestamp_column="period_start",
                duration_hours_column="hours",
                signal_mappings=[
                    CatalogSignalMappingRequest(
                        source_column="demand", signal_key="load_demand_mw"
                    ),
                ],
            ),
        )
        self.demand_set = self.store.import_time_series_catalog_set(
            scenario_id=self.scenario["id"],
            source={
                "id": "csv_source_demand",
                "original_filename": "demand.csv",
                "media_type": "text/csv",
                "checksum": "sha256:demand",
            },
            prepared_import=demand_prepared,
        )
        self.combined_set = self.store.apply_time_series_combination(
            project_id=self.project["id"],
            transformation_type="combine_signals",
            raw_parameters={
                "inputs": [
                    {
                        "time_series_set_id": self.price_set["id"],
                        "signal_keys": ["import_price_usd_per_mwh"],
                    },
                    {
                        "time_series_set_id": self.demand_set["id"],
                        "signal_keys": ["load_demand_mw"],
                    },
                ]
            },
        )

    def test_editing_any_input_marks_the_combined_set_stale(self):
        self.store.edit_time_series_set_values(
            project_id=self.project["id"],
            time_series_set_id=self.demand_set["id"],
            edits=[
                CatalogValueEdit(
                    period_index=0, signal_key="load_demand_mw", value_text="500.0"
                )
            ],
        )

        staleness = self.store.evaluate_time_series_set_staleness(
            self.project["id"], self.combined_set["id"]
        )

        self.assertTrue(staleness["stale"])
        self.assertEqual(
            staleness["reasons"][0]["dependency_id"], str(self.demand_set["id"])
        )

    def test_regenerating_a_combined_set_pulls_current_values_from_every_input(self):
        self.store.edit_time_series_set_values(
            project_id=self.project["id"],
            time_series_set_id=self.demand_set["id"],
            edits=[
                CatalogValueEdit(
                    period_index=0, signal_key="load_demand_mw", value_text="500.0"
                )
            ],
        )

        regenerated = self.store.regenerate_derived_time_series_set(
            project_id=self.project["id"],
            time_series_set_id=self.combined_set["id"],
        )

        self.assertEqual(regenerated["id"], self.combined_set["id"])
        self.assertEqual(regenerated["revision_number"], 2)
        values_by_key = {
            (value["period_index"], value["signal_key"]): value["value_numeric"]
            for value in regenerated["values"]
        }
        self.assertAlmostEqual(values_by_key[(0, "load_demand_mw")], 500.0)
        self.assertAlmostEqual(values_by_key[(0, "import_price_usd_per_mwh")], 50.0)
        staleness = self.store.evaluate_time_series_set_staleness(
            self.project["id"], self.combined_set["id"]
        )
        self.assertFalse(staleness["stale"])


def grid_battery_draft_document():
    return {
        "schema_version": "bess_editor_draft.v1",
        "case": {"name": "grid_battery_case", "description": ""},
        "pcc": {"id": "bus_1", "type": "bus"},
        "grid": {
            "id": "grid_1",
            "import_power_max_mw": 10.0,
            "export_power_max_mw": 10.0,
            "prevent_simultaneous_grid_import_export": True,
        },
        "assets": [
            {
                "id": "battery_1",
                "type": "battery",
                "charge_power_max_mw": 4.0,
                "discharge_power_max_mw": 4.0,
                "energy_min_mwh": 0.0,
                "energy_max_mwh": 8.0,
                "initial_energy_mwh": 4.0,
                "charge_efficiency": 0.95,
                "discharge_efficiency": 0.95,
                "degradation_cost_per_mwh_delta_soc": 0.0,
                "terminal_condition": "none",
                "prevent_simultaneous_charge_discharge": True,
                "degradation_linear_delta_soc": True,
            },
        ],
        "time_series": {"sources": []},
        "solver": {"name": "HiGHS", "options": {}},
    }


def price_import_request(*, version_label="v1"):
    return CatalogImportRequest(
        set_name="Spot price",
        version_label=version_label,
        data_kind="real",
        timezone="America/Santiago",
        timestamp_column="period_start",
        duration_hours_column="hours",
        signal_mappings=[
            CatalogSignalMappingRequest(
                source_column="spot_price", signal_key="import_price_usd_per_mwh"
            ),
        ],
    )


def price_rows(start, count, *, value=50.0):
    rows = []
    for hour in range(count):
        instant = start + timedelta(hours=hour)
        rows.append(
            {
                "period_start": instant.isoformat(),
                "hours": "1.0",
                "spot_price": str(value + hour),
            }
        )
    return rows


class VariantBoundToDerivedSetTests(unittest.TestCase):
    """A variant bound to a derived set composes with the TS-3 fail-closed gates."""

    def setUp(self):
        from app.variant_staleness import VariantStaleError

        self.VariantStaleError = VariantStaleError
        self.store = AnalystStore("sqlite:///:memory:")
        self.addCleanup(self.store.close)
        self.project = self.store.create_project(name="TS6-005 variant project")
        self.scenario = self.store.create_scenario(
            project_id=self.project["id"], name="TS6-005 variant scenario"
        )
        self.store.create_or_replace_scenario_draft(
            scenario_id=self.scenario["id"], document=grid_battery_draft_document()
        )
        self.case = self.store.get_or_create_case_for_scenario(self.scenario["id"])
        self.variant = self.store.get_or_create_default_input_variant(self.case["id"])

        prepared_price = prepare_time_series_catalog_import(
            rows=price_rows(datetime(2026, 1, 1), 3),
            request=price_import_request(),
        )
        self.price_set = self.store.import_time_series_catalog_set(
            scenario_id=self.scenario["id"],
            source={
                "id": "csv_source_price",
                "original_filename": "price.csv",
                "media_type": "text/csv",
                "checksum": "sha256:price",
            },
            prepared_import=prepared_price,
        )
        self.derived_set = self.store.apply_time_series_transformation(
            project_id=self.project["id"],
            time_series_set_id=self.price_set["id"],
            transformation_type="scale_signal",
            raw_parameters={
                "signal_key": "import_price_usd_per_mwh",
                "scale_factor": 2.0,
            },
        )
        self.store.upsert_case_time_series_binding(
            case_input_variant_id=self.variant["id"],
            signal_key="import_price_usd_per_mwh",
            time_series_set_id=self.derived_set["id"],
        )

    def _edit_price_source(self):
        self.store.edit_time_series_set_values(
            project_id=self.project["id"],
            time_series_set_id=self.price_set["id"],
            edits=[
                CatalogValueEdit(
                    period_index=0,
                    signal_key="import_price_usd_per_mwh",
                    value_text="999.0",
                )
            ],
        )

    def _materialize(self):
        return self.store.materialize_system_case_for_variant(
            scenario_id=self.scenario["id"],
            case_input_variant_id=self.variant["id"],
            range_start=self.derived_set["horizon"]["start"],
            range_end=self.derived_set["horizon"]["end"],
        )

    def _validate(self):
        return self.store.validate_case_input_variant(
            scenario_id=self.scenario["id"],
            case_input_variant_id=self.variant["id"],
            range_start=self.derived_set["horizon"]["start"],
            range_end=self.derived_set["horizon"]["end"],
        )

    def _staleness(self):
        return self.store.evaluate_case_input_variant_staleness(
            scenario_id=self.scenario["id"], case_input_variant_id=self.variant["id"]
        )

    def test_validated_variant_goes_stale_when_the_derived_sets_source_moves(self):
        self._materialize()
        self.assertFalse(self._staleness()["stale"])

        self._edit_price_source()

        staleness = self._staleness()
        self.assertTrue(staleness["stale"])
        self.assertIn(
            "time_series_set_derived_staleness",
            [reason["dependency_type"] for reason in staleness["reasons"]],
        )
        with self.assertRaises(self.VariantStaleError):
            self._materialize()

    def test_unvalidated_variant_is_also_blocked_while_the_derived_set_is_stale(self):
        self._edit_price_source()

        with self.assertRaises(self.VariantStaleError):
            self._materialize()

    def test_revalidation_stays_blocked_until_the_derived_set_is_regenerated(self):
        self._materialize()
        self._edit_price_source()

        with self.assertRaises(self.VariantStaleError):
            self._validate()

    def test_regenerating_and_revalidating_unblocks_the_variant(self):
        self._materialize()
        self._edit_price_source()

        self.store.regenerate_derived_time_series_set(
            project_id=self.project["id"],
            time_series_set_id=self.derived_set["id"],
        )
        staleness = self._staleness()
        self.assertTrue(staleness["stale"])
        self.assertEqual(
            [reason["dependency_type"] for reason in staleness["reasons"]],
            ["time_series_set"],
        )

        self._validate()
        self.assertFalse(self._staleness()["stale"])
        materialized = self._materialize()
        self.assertTrue(materialized["system_case"]["time_series"])


class DerivedStalenessApiTests(unittest.TestCase):
    def setUp(self):
        from fastapi.testclient import TestClient

        from app.main import create_app
        from app.validation import ValidationResult

        class StubValidationService:
            def validate_text(self, candidate_text):
                return ValidationResult(
                    ok=True, phase="julia", message="ok", payload={"status": "ok"}
                )

        class RecordingRunQueue:
            def enqueue(self, run_id):
                pass

            def stop(self):
                pass

        self.client = TestClient(
            create_app(
                validation_service=StubValidationService(),
                database_url="sqlite:///:memory:",
                run_queue=RecordingRunQueue(),
            )
        )
        self.store = self.client.app.state.analyst_store
        self.project = self.store.create_project(name="TS6-005 API project")
        self.scenario = self.store.create_scenario(
            project_id=self.project["id"], name="TS6-005 API scenario"
        )
        prepared = prepare_time_series_catalog_import(
            rows=demand_price_rows(datetime(2026, 1, 1), 3),
            request=demand_price_import_request(),
        )
        self.source_set = self.store.import_time_series_catalog_set(
            scenario_id=self.scenario["id"],
            source={
                "id": "csv_source_api",
                "original_filename": "demand_price.csv",
                "media_type": "text/csv",
                "checksum": "sha256:api",
            },
            prepared_import=prepared,
        )
        self.derived_set = self.store.apply_time_series_transformation(
            project_id=self.project["id"],
            time_series_set_id=self.source_set["id"],
            transformation_type="scale_signal",
            raw_parameters={"signal_key": "load_demand_mw", "scale_factor": 2.0},
        )
        self.store.edit_time_series_set_values(
            project_id=self.project["id"],
            time_series_set_id=self.source_set["id"],
            edits=[
                CatalogValueEdit(
                    period_index=0, signal_key="load_demand_mw", value_text="200.0"
                )
            ],
        )

    def test_detail_endpoint_reports_derived_staleness(self):
        response = self.client.get(
            f"/api/projects/{self.project['id']}/time-series-sets/"
            f"{self.derived_set['id']}"
        )

        self.assertEqual(response.status_code, 200)
        staleness = response.json()["time_series_set"]["staleness"]
        self.assertTrue(staleness["stale"])
        self.assertEqual(
            staleness["reasons"][0]["dependency_type"], "time_series_set"
        )

    def test_list_endpoint_flags_stale_derived_sets(self):
        response = self.client.get(
            f"/api/projects/{self.project['id']}/time-series-sets"
        )

        self.assertEqual(response.status_code, 200)
        sets_by_id = {
            entry["id"]: entry for entry in response.json()["time_series_sets"]
        }
        self.assertTrue(sets_by_id[self.derived_set["id"]]["stale"])
        self.assertFalse(sets_by_id[self.source_set["id"]]["stale"])

    def test_regenerate_endpoint_produces_a_new_revision(self):
        response = self.client.post(
            f"/api/projects/{self.project['id']}/time-series-sets/"
            f"{self.derived_set['id']}/regenerate"
        )

        self.assertEqual(response.status_code, 200)
        regenerated = response.json()["time_series_set"]
        self.assertEqual(regenerated["id"], self.derived_set["id"])
        self.assertEqual(regenerated["revision_number"], 2)
        self.assertFalse(regenerated["staleness"]["stale"])

    def test_regenerate_endpoint_rejects_non_derived_sets(self):
        response = self.client.post(
            f"/api/projects/{self.project['id']}/time-series-sets/"
            f"{self.source_set['id']}/regenerate"
        )

        self.assertEqual(response.status_code, 400)

    def test_regenerate_endpoint_returns_404_for_unknown_sets(self):
        response = self.client.post(
            f"/api/projects/{self.project['id']}/time-series-sets/999999/regenerate"
        )

        self.assertEqual(response.status_code, 404)


if __name__ == "__main__":
    unittest.main()
