"""Canonical association, binding and audit structures for TS7-004.

These tables expand beside the legacy writer in the same physical space as the
TS7 canonical content model: ``ts_next`` on PostgreSQL and ``_next`` on SQLite.
"""

from __future__ import annotations

from app.time_series_canonical import canonical_space_table_name


LINK_LEDGER_IMMUTABLE = "TS_LINK_LEDGER_IMMUTABLE"
LINK_HISTORY_IMMUTABLE = "TS_LINK_HISTORY_IMMUTABLE"

LINK_LAYER_LOGICAL_TABLES = (
    "time_series_catalog_associations",
    "case_time_series_bindings",
    "time_series_link_validations",
    "time_series_link_events",
    "time_series_scope_events",
)


def link_layer_table_names(backend: str) -> dict[str, str]:
    """Physical name of every TS7-004 table for one database engine."""

    return {
        logical: canonical_space_table_name(logical, backend)
        for logical in LINK_LAYER_LOGICAL_TABLES
    }


def link_layer_schema_statements(backend: str) -> list[str]:
    """Additive DDL for the two link layers and their three audit ledgers."""

    postgres = backend == "postgresql"
    table = link_layer_table_names(backend)
    canonical = {
        logical: canonical_space_table_name(logical, backend)
        for logical in (
            "time_series_sets",
            "time_series_signals",
            "time_series_set_revisions",
            "time_series_revision_signals",
            "linkable_objects",
        )
    }
    identity = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if postgres
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    reference = "BIGINT" if postgres else "INTEGER"

    statements = [
        f"""
        CREATE TABLE IF NOT EXISTS {table['time_series_catalog_associations']} (
            id {identity},
            signal_id {reference} NOT NULL,
            time_series_set_id {reference} NOT NULL,
            series_kind TEXT NOT NULL DEFAULT 'catalog',
            linkable_object_id {reference} NOT NULL
                REFERENCES {canonical['linkable_objects']}(id),
            binding_role_id {reference} NOT NULL
                REFERENCES time_series_binding_roles(id),
            compatibility_rule_id {reference} NOT NULL
                REFERENCES time_series_role_compatibilities(id),
            supersedes_association_id {reference}
                REFERENCES {table['time_series_catalog_associations']}(id),
            lifecycle_revision INTEGER NOT NULL DEFAULT 1,
            status TEXT NOT NULL DEFAULT 'active',
            created_at TEXT NOT NULL,
            created_by TEXT NOT NULL,
            archived_at TEXT,
            archived_by TEXT,
            archived_reason_code TEXT,
            archived_reason_text TEXT,
            metadata_json TEXT NOT NULL DEFAULT '{{}}',
            CHECK (series_kind = 'catalog'),
            CHECK (lifecycle_revision > 0),
            CHECK (status IN ('active', 'archived')),
            CONSTRAINT ts7_association_archive_evidence_ck CHECK (
                (status = 'active'
                 AND archived_at IS NULL
                 AND archived_by IS NULL
                 AND archived_reason_code IS NULL
                 AND archived_reason_text IS NULL)
                OR
                (status = 'archived'
                 AND archived_at IS NOT NULL
                 AND archived_at >= created_at
                 AND archived_by IS NOT NULL
                 AND TRIM(archived_by) <> ''
                 AND archived_reason_code IS NOT NULL
                 AND TRIM(archived_reason_code) <> '')
            ),
            FOREIGN KEY (signal_id, time_series_set_id)
                REFERENCES {canonical['time_series_signals']}
                (id, time_series_set_id),
            FOREIGN KEY (time_series_set_id, series_kind)
                REFERENCES {canonical['time_series_sets']}(id, series_kind)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS {table['case_time_series_bindings']} (
            id {identity},
            case_input_variant_id {reference} NOT NULL
                REFERENCES case_input_variants(id),
            linkable_object_id {reference} NOT NULL
                REFERENCES {canonical['linkable_objects']}(id),
            binding_role_id {reference} NOT NULL
                REFERENCES time_series_binding_roles(id),
            signal_id {reference} NOT NULL,
            time_series_set_id {reference} NOT NULL,
            set_revision_id {reference} NOT NULL,
            bound_content_hash TEXT NOT NULL,
            source_kind TEXT NOT NULL,
            source_owner_linkable_object_id {reference},
            catalog_association_id {reference}
                REFERENCES {table['time_series_catalog_associations']}(id),
            compatibility_rule_id {reference} NOT NULL
                REFERENCES time_series_role_compatibilities(id),
            required INTEGER NOT NULL DEFAULT 1,
            status TEXT NOT NULL DEFAULT 'active',
            supersedes_binding_id {reference}
                REFERENCES {table['case_time_series_bindings']}(id),
            lifecycle_revision INTEGER NOT NULL DEFAULT 1,
            change_reason_code TEXT NOT NULL,
            change_reason_text TEXT,
            validated_at TEXT,
            superseded_at TEXT,
            superseded_by TEXT,
            removed_at TEXT,
            removed_by TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            created_by TEXT NOT NULL,
            updated_by TEXT NOT NULL,
            metadata_json TEXT NOT NULL DEFAULT '{{}}',
            CHECK (source_kind IN ('catalog', 'object_specific')),
            CHECK (required IN (0, 1)),
            CHECK (status IN ('active', 'superseded', 'removed')),
            CHECK (lifecycle_revision > 0),
            CONSTRAINT ts7_binding_change_reason_ck
                CHECK (TRIM(change_reason_code) <> ''),
            CONSTRAINT ts7_binding_updated_at_ck
                CHECK (updated_at >= created_at),
            CONSTRAINT ts7_binding_lifecycle_evidence_ck CHECK (
                (status = 'active'
                 AND superseded_at IS NULL
                 AND superseded_by IS NULL
                 AND removed_at IS NULL
                 AND removed_by IS NULL)
                OR
                (status = 'superseded'
                 AND superseded_at IS NOT NULL
                 AND superseded_at >= created_at
                 AND superseded_by IS NOT NULL
                 AND TRIM(superseded_by) <> ''
                 AND removed_at IS NULL
                 AND removed_by IS NULL)
                OR
                (status = 'removed'
                 AND removed_at IS NOT NULL
                 AND removed_at >= created_at
                 AND removed_by IS NOT NULL
                 AND TRIM(removed_by) <> ''
                 AND superseded_at IS NULL
                 AND superseded_by IS NULL)
            ),
            FOREIGN KEY (signal_id, time_series_set_id)
                REFERENCES {canonical['time_series_signals']}
                (id, time_series_set_id),
            FOREIGN KEY (set_revision_id, time_series_set_id)
                REFERENCES {canonical['time_series_set_revisions']}
                (id, time_series_set_id),
            FOREIGN KEY (set_revision_id, signal_id)
                REFERENCES {canonical['time_series_revision_signals']}
                (set_revision_id, signal_id),
            FOREIGN KEY (
                set_revision_id, time_series_set_id, bound_content_hash
            ) REFERENCES {canonical['time_series_set_revisions']}
                (id, time_series_set_id, content_hash),
            FOREIGN KEY (time_series_set_id, source_kind)
                REFERENCES {canonical['time_series_sets']}(id, series_kind),
            FOREIGN KEY (
                time_series_set_id, source_owner_linkable_object_id
            ) REFERENCES {canonical['time_series_sets']}
                (id, owner_linkable_object_id),
            CHECK (
                (source_kind = 'catalog'
                 AND source_owner_linkable_object_id IS NULL)
                OR
                (source_kind = 'object_specific'
                 AND source_owner_linkable_object_id IS NOT NULL
                 AND source_owner_linkable_object_id = linkable_object_id
                 AND catalog_association_id IS NULL)
            )
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS {table['time_series_link_validations']} (
            id {identity},
            catalog_association_id {reference}
                REFERENCES {table['time_series_catalog_associations']}(id),
            binding_id {reference}
                REFERENCES {table['case_time_series_bindings']}(id),
            subject_lifecycle_revision INTEGER NOT NULL,
            validation_mode TEXT NOT NULL,
            validated_set_revision_id {reference} NOT NULL
                REFERENCES {canonical['time_series_set_revisions']}(id),
            observed_current_revision_id {reference} NOT NULL
                REFERENCES {canonical['time_series_set_revisions']}(id),
            compatibility_rule_id {reference} NOT NULL
                REFERENCES time_series_role_compatibilities(id),
            compatibility_fingerprint TEXT NOT NULL,
            object_scope_fingerprint TEXT NOT NULL,
            variant_dependency_fingerprint TEXT,
            validated_range_json TEXT,
            validated_at TEXT NOT NULL,
            validated_by TEXT NOT NULL,
            reason_code TEXT NOT NULL,
            reason_text TEXT,
            CHECK (subject_lifecycle_revision > 0),
            CHECK (validation_mode IN (
                'association_current', 'binding_current', 'binding_pinned'
            )),
            CHECK (
                (catalog_association_id IS NOT NULL AND binding_id IS NULL)
                OR
                (catalog_association_id IS NULL AND binding_id IS NOT NULL)
            )
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS {table['time_series_link_events']} (
            id {identity},
            batch_id TEXT,
            catalog_association_id {reference}
                REFERENCES {table['time_series_catalog_associations']}(id),
            binding_id {reference}
                REFERENCES {table['case_time_series_bindings']}(id),
            event_type TEXT NOT NULL,
            actor_user_id {reference} REFERENCES users(id),
            actor_identity_snapshot TEXT NOT NULL,
            actor_role_snapshot TEXT NOT NULL,
            reason_code TEXT NOT NULL,
            reason_text TEXT,
            before_json TEXT NOT NULL DEFAULT '{{}}',
            after_json TEXT NOT NULL DEFAULT '{{}}',
            request_id TEXT NOT NULL,
            occurred_at TEXT NOT NULL,
            CHECK (
                (catalog_association_id IS NOT NULL AND binding_id IS NULL)
                OR
                (catalog_association_id IS NULL AND binding_id IS NOT NULL)
            )
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS {table['time_series_scope_events']} (
            id {identity},
            time_series_set_id {reference} NOT NULL
                REFERENCES {canonical['time_series_sets']}(id),
            event_type TEXT NOT NULL,
            from_scope TEXT,
            to_scope TEXT NOT NULL,
            scope_revision INTEGER NOT NULL,
            owner_project_id {reference} NOT NULL REFERENCES projects(id),
            observed_set_revision_id {reference}
                REFERENCES {canonical['time_series_set_revisions']}(id),
            observed_content_hash TEXT,
            actor_user_id {reference} NOT NULL REFERENCES users(id),
            actor_identity_snapshot TEXT NOT NULL,
            actor_role_snapshot TEXT NOT NULL,
            reason_code TEXT NOT NULL,
            reason_text TEXT NOT NULL,
            impact_json TEXT NOT NULL DEFAULT '{{}}',
            request_id TEXT NOT NULL,
            idempotency_key TEXT NOT NULL,
            occurred_at TEXT NOT NULL,
            CHECK (event_type IN (
                'created_project', 'promoted_global', 'demoted_project'
            )),
            CHECK (from_scope IS NULL OR from_scope IN ('project', 'global')),
            CHECK (to_scope IN ('project', 'global')),
            CHECK (scope_revision > 0),
            UNIQUE (time_series_set_id, scope_revision),
            UNIQUE (actor_user_id, idempotency_key)
        )
        """,
    ]
    statements.append(
        f"""
        CREATE UNIQUE INDEX IF NOT EXISTS
            time_series_catalog_associations_next_one_active_uk
            ON {table['time_series_catalog_associations']} (
                signal_id, linkable_object_id, binding_role_id
            )
            WHERE status = 'active'
        """
    )
    statements.append(
        f"""
        CREATE UNIQUE INDEX IF NOT EXISTS
            case_time_series_bindings_next_one_active_uk
            ON {table['case_time_series_bindings']} (
                case_input_variant_id, linkable_object_id, binding_role_id
            )
            WHERE status = 'active'
        """
    )
    return [statement.strip() for statement in statements]


def link_layer_guard_script(backend: str) -> str:
    """Make all three audit ledgers observably insert-only."""

    table = link_layer_table_names(backend)
    ledgers = (
        "time_series_link_validations",
        "time_series_link_events",
        "time_series_scope_events",
    )
    if backend == "postgresql":
        statements = [
            f"""
            CREATE OR REPLACE FUNCTION ts_next.reject_link_ledger_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION '{LINK_LEDGER_IMMUTABLE}';
            END;
            $$ LANGUAGE plpgsql;
            """
        ]
        for logical in ledgers:
            trigger_prefix = f"ts_next_{logical}"
            for operation in ("UPDATE", "DELETE"):
                label = operation.lower()
                statements.append(
                    f"""
                    DROP TRIGGER IF EXISTS {trigger_prefix}_{label}
                    ON {table[logical]};
                    CREATE TRIGGER {trigger_prefix}_{label}
                    BEFORE {operation} ON {table[logical]}
                    FOR EACH ROW
                    EXECUTE FUNCTION ts_next.reject_link_ledger_mutation();
                    """
                )
        return "\n".join(statements)

    statements = []
    for logical in ledgers:
        trigger_prefix = f"ts_next_{logical}"
        for operation in ("UPDATE", "DELETE"):
            label = operation.lower()
            statements.append(
                f"""
                DROP TRIGGER IF EXISTS {trigger_prefix}_{label};
                CREATE TRIGGER {trigger_prefix}_{label}
                BEFORE {operation} ON {table[logical]}
                FOR EACH ROW
                BEGIN
                    SELECT RAISE(ABORT, '{LINK_LEDGER_IMMUTABLE}');
                END;
                """
            )
    return "\n".join(statements)


def link_layer_constraint_upgrade_script(backend: str) -> str | None:
    """Converge PostgreSQL databases that already carry an earlier C2 table."""

    if backend != "postgresql":
        return None
    table = link_layer_table_names(backend)
    associations = table["time_series_catalog_associations"]
    bindings = table["case_time_series_bindings"]
    return f"""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
            WHERE conname = 'ts7_association_archive_evidence_ck'
              AND conrelid = '{associations}'::regclass
        ) THEN
            ALTER TABLE {associations}
            ADD CONSTRAINT ts7_association_archive_evidence_ck CHECK (
                (status = 'active'
                 AND archived_at IS NULL
                 AND archived_by IS NULL
                 AND archived_reason_code IS NULL
                 AND archived_reason_text IS NULL)
                OR
                (status = 'archived'
                 AND archived_at IS NOT NULL
                 AND archived_at >= created_at
                 AND archived_by IS NOT NULL
                 AND TRIM(archived_by) <> ''
                 AND archived_reason_code IS NOT NULL
                 AND TRIM(archived_reason_code) <> '')
            );
        END IF;
    END $$;

    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
            WHERE conname = 'ts7_binding_change_reason_ck'
              AND conrelid = '{bindings}'::regclass
        ) THEN
            ALTER TABLE {bindings}
            ADD CONSTRAINT ts7_binding_change_reason_ck
                CHECK (TRIM(change_reason_code) <> '');
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
            WHERE conname = 'ts7_binding_updated_at_ck'
              AND conrelid = '{bindings}'::regclass
        ) THEN
            ALTER TABLE {bindings}
            ADD CONSTRAINT ts7_binding_updated_at_ck
                CHECK (updated_at >= created_at);
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
            WHERE conname = 'ts7_binding_lifecycle_evidence_ck'
              AND conrelid = '{bindings}'::regclass
        ) THEN
            ALTER TABLE {bindings}
            ADD CONSTRAINT ts7_binding_lifecycle_evidence_ck CHECK (
                (status = 'active'
                 AND superseded_at IS NULL
                 AND superseded_by IS NULL
                 AND removed_at IS NULL
                 AND removed_by IS NULL)
                OR
                (status = 'superseded'
                 AND superseded_at IS NOT NULL
                 AND superseded_at >= created_at
                 AND superseded_by IS NOT NULL
                 AND TRIM(superseded_by) <> ''
                 AND removed_at IS NULL
                 AND removed_by IS NULL)
                OR
                (status = 'removed'
                 AND removed_at IS NOT NULL
                 AND removed_at >= created_at
                 AND removed_by IS NOT NULL
                 AND TRIM(removed_by) <> ''
                 AND superseded_at IS NULL
                 AND superseded_by IS NULL)
            );
        END IF;
    END $$;
    """


def link_history_guard_script(backend: str) -> str:
    """Keep link identity and both supersession chains append-only."""

    table = link_layer_table_names(backend)
    associations = table["time_series_catalog_associations"]
    bindings = table["case_time_series_bindings"]
    if backend == "postgresql":
        return f"""
        CREATE OR REPLACE FUNCTION ts_next.reject_association_history_mutation()
        RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION '{LINK_HISTORY_IMMUTABLE}';
            END IF;
            IF OLD.id IS DISTINCT FROM NEW.id
               OR OLD.signal_id IS DISTINCT FROM NEW.signal_id
               OR OLD.time_series_set_id IS DISTINCT FROM NEW.time_series_set_id
               OR OLD.series_kind IS DISTINCT FROM NEW.series_kind
               OR OLD.linkable_object_id IS DISTINCT FROM NEW.linkable_object_id
               OR OLD.binding_role_id IS DISTINCT FROM NEW.binding_role_id
               OR OLD.compatibility_rule_id IS DISTINCT FROM NEW.compatibility_rule_id
               OR OLD.supersedes_association_id IS DISTINCT FROM NEW.supersedes_association_id
               OR OLD.created_at IS DISTINCT FROM NEW.created_at
               OR OLD.created_by IS DISTINCT FROM NEW.created_by THEN
                RAISE EXCEPTION '{LINK_HISTORY_IMMUTABLE}';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        DROP TRIGGER IF EXISTS ts_next_association_history_immutable
        ON {associations};
        CREATE TRIGGER ts_next_association_history_immutable
        BEFORE UPDATE OR DELETE ON {associations}
        FOR EACH ROW
        EXECUTE FUNCTION ts_next.reject_association_history_mutation();

        CREATE OR REPLACE FUNCTION ts_next.reject_binding_history_mutation()
        RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION '{LINK_HISTORY_IMMUTABLE}';
            END IF;
            IF OLD.id IS DISTINCT FROM NEW.id
               OR OLD.case_input_variant_id IS DISTINCT FROM NEW.case_input_variant_id
               OR OLD.linkable_object_id IS DISTINCT FROM NEW.linkable_object_id
               OR OLD.binding_role_id IS DISTINCT FROM NEW.binding_role_id
               OR OLD.signal_id IS DISTINCT FROM NEW.signal_id
               OR OLD.time_series_set_id IS DISTINCT FROM NEW.time_series_set_id
               OR OLD.set_revision_id IS DISTINCT FROM NEW.set_revision_id
               OR OLD.bound_content_hash IS DISTINCT FROM NEW.bound_content_hash
               OR OLD.source_kind IS DISTINCT FROM NEW.source_kind
               OR OLD.source_owner_linkable_object_id IS DISTINCT FROM NEW.source_owner_linkable_object_id
               OR OLD.catalog_association_id IS DISTINCT FROM NEW.catalog_association_id
               OR OLD.compatibility_rule_id IS DISTINCT FROM NEW.compatibility_rule_id
               OR OLD.required IS DISTINCT FROM NEW.required
               OR OLD.supersedes_binding_id IS DISTINCT FROM NEW.supersedes_binding_id
               OR OLD.change_reason_code IS DISTINCT FROM NEW.change_reason_code
               OR OLD.change_reason_text IS DISTINCT FROM NEW.change_reason_text
               OR OLD.created_at IS DISTINCT FROM NEW.created_at
               OR OLD.created_by IS DISTINCT FROM NEW.created_by THEN
                RAISE EXCEPTION '{LINK_HISTORY_IMMUTABLE}';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        DROP TRIGGER IF EXISTS ts_next_binding_history_immutable
        ON {bindings};
        CREATE TRIGGER ts_next_binding_history_immutable
        BEFORE UPDATE OR DELETE ON {bindings}
        FOR EACH ROW
        EXECUTE FUNCTION ts_next.reject_binding_history_mutation();
        """

    return f"""
    DROP TRIGGER IF EXISTS ts_next_association_identity_immutable;
    CREATE TRIGGER ts_next_association_identity_immutable
    BEFORE UPDATE ON {associations}
    FOR EACH ROW WHEN
           OLD.id IS NOT NEW.id
        OR OLD.signal_id IS NOT NEW.signal_id
        OR OLD.time_series_set_id IS NOT NEW.time_series_set_id
        OR OLD.series_kind IS NOT NEW.series_kind
        OR OLD.linkable_object_id IS NOT NEW.linkable_object_id
        OR OLD.binding_role_id IS NOT NEW.binding_role_id
        OR OLD.compatibility_rule_id IS NOT NEW.compatibility_rule_id
        OR OLD.supersedes_association_id IS NOT NEW.supersedes_association_id
        OR OLD.created_at IS NOT NEW.created_at
        OR OLD.created_by IS NOT NEW.created_by
    BEGIN
        SELECT RAISE(ABORT, '{LINK_HISTORY_IMMUTABLE}');
    END;

    DROP TRIGGER IF EXISTS ts_next_association_delete_immutable;
    CREATE TRIGGER ts_next_association_delete_immutable
    BEFORE DELETE ON {associations}
    FOR EACH ROW
    BEGIN
        SELECT RAISE(ABORT, '{LINK_HISTORY_IMMUTABLE}');
    END;

    DROP TRIGGER IF EXISTS ts_next_binding_identity_immutable;
    CREATE TRIGGER ts_next_binding_identity_immutable
    BEFORE UPDATE ON {bindings}
    FOR EACH ROW WHEN
           OLD.id IS NOT NEW.id
        OR OLD.case_input_variant_id IS NOT NEW.case_input_variant_id
        OR OLD.linkable_object_id IS NOT NEW.linkable_object_id
        OR OLD.binding_role_id IS NOT NEW.binding_role_id
        OR OLD.signal_id IS NOT NEW.signal_id
        OR OLD.time_series_set_id IS NOT NEW.time_series_set_id
        OR OLD.set_revision_id IS NOT NEW.set_revision_id
        OR OLD.bound_content_hash IS NOT NEW.bound_content_hash
        OR OLD.source_kind IS NOT NEW.source_kind
        OR OLD.source_owner_linkable_object_id IS NOT NEW.source_owner_linkable_object_id
        OR OLD.catalog_association_id IS NOT NEW.catalog_association_id
        OR OLD.compatibility_rule_id IS NOT NEW.compatibility_rule_id
        OR OLD.required IS NOT NEW.required
        OR OLD.supersedes_binding_id IS NOT NEW.supersedes_binding_id
        OR OLD.change_reason_code IS NOT NEW.change_reason_code
        OR OLD.change_reason_text IS NOT NEW.change_reason_text
        OR OLD.created_at IS NOT NEW.created_at
        OR OLD.created_by IS NOT NEW.created_by
    BEGIN
        SELECT RAISE(ABORT, '{LINK_HISTORY_IMMUTABLE}');
    END;

    DROP TRIGGER IF EXISTS ts_next_binding_delete_immutable;
    CREATE TRIGGER ts_next_binding_delete_immutable
    BEFORE DELETE ON {bindings}
    FOR EACH ROW
    BEGIN
        SELECT RAISE(ABORT, '{LINK_HISTORY_IMMUTABLE}');
    END;
    """
