"""Canonical time-series content model (TS-7 chapters 2.1, 2.3, 2.7, 10.1).

The canonical model lives in its own physical space beside the legacy tables:
schema ``ts_next`` on PostgreSQL and a ``_next`` suffix on SQLite. The current
writer deletes and recreates legacy signals and periods on some replacements, so
legacy and canonical children never share a table (chapter 10.1).
"""

from __future__ import annotations

import hashlib


CANONICAL_CONTENT_MODEL_VERSION = 1

CANONICAL_SCHEMA_NAME = "ts_next"
CANONICAL_TABLE_SUFFIX = "_next"

CANONICAL_LOGICAL_TABLES = (
    "time_series_sources",
    "time_series_sets",
    "time_series_signals",
    "time_series_set_revisions",
    "time_series_revision_signals",
    "time_series_periods",
    "time_series_values",
    "time_series_revision_lineage",
)

# Canonical tables whose surrogate key is generated by the engine. The
# PostgreSQL compatibility layer only appends ``RETURNING id`` for names it
# knows, and it cannot know a schema-qualified one, so the canonical writer
# always spells ``RETURNING id`` out for these tables instead.
CANONICAL_IDENTITY_TABLES = (
    "time_series_sources",
    "time_series_sets",
    "time_series_signals",
    "time_series_set_revisions",
    "time_series_periods",
)


def canonical_table_names(backend: str) -> dict[str, str]:
    """Physical name of every canonical table for the given engine."""

    return {
        logical: canonical_table_name(logical, backend)
        for logical in CANONICAL_LOGICAL_TABLES
    }


def canonical_table_name(logical: str, backend: str) -> str:
    if logical not in CANONICAL_LOGICAL_TABLES:
        raise KeyError(f"unknown canonical table: {logical}")
    return canonical_space_table_name(logical, backend)


def canonical_space_table_name(logical: str, backend: str) -> str:
    """Physical name of any table that lives in the canonical space.

    The closed register of linkable objects (TS7-003) shares this space with the
    content model, so both expand beside the legacy tables under one convention.
    """

    if backend == "postgresql":
        return f"{CANONICAL_SCHEMA_NAME}.{logical}"
    return f"{logical}{CANONICAL_TABLE_SUFFIX}"


def _index_name(logical: str, suffix: str) -> str:
    return f"{logical}{CANONICAL_TABLE_SUFFIX}_{suffix}"


def canonical_schema_statements(backend: str) -> list[str]:
    """DDL that lands the canonical content model on the given engine."""

    postgres = backend == "postgresql"
    table = canonical_table_names(backend)
    identity = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if postgres
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    reference = "BIGINT" if postgres else "INTEGER"
    # PostgreSQL ``REAL`` is single precision; the canonical hash is computed
    # over the stored snapshot, so both engines must keep the same 64 bits.
    double = "DOUBLE PRECISION" if postgres else "REAL"
    empty_json = "'{}'"

    statements: list[str] = []
    if postgres:
        statements.append(f"CREATE SCHEMA IF NOT EXISTS {CANONICAL_SCHEMA_NAME}")

    statements.append(
        f"""
        CREATE TABLE IF NOT EXISTS {table['time_series_sources']} (
            id {identity},
            project_id {reference} NOT NULL REFERENCES projects(id),
            source_key TEXT NOT NULL,
            kind TEXT NOT NULL,
            original_filename TEXT NOT NULL DEFAULT '',
            media_type TEXT NOT NULL DEFAULT '',
            checksum TEXT NOT NULL DEFAULT '',
            stored_path TEXT NOT NULL DEFAULT '',
            selected_sheet TEXT,
            metadata_json TEXT NOT NULL DEFAULT {empty_json},
            created_at TEXT NOT NULL,
            created_by TEXT NOT NULL,
            UNIQUE (project_id, source_key),
            CHECK (kind IN ('api', 'csv', 'xlsx', 'manual', 'migration'))
        )
        """
    )

    # The project is propagated only where a real composite foreign key allows
    # it (chapter 9.6): an object-specific set names its owner and its project
    # together, so a set owned by an object of another project never commits.
    register = canonical_space_table_name("linkable_objects", backend)
    statements.append(
        f"""
        CREATE TABLE IF NOT EXISTS {table['time_series_sets']} (
            id {identity},
            owner_project_id {reference} NOT NULL REFERENCES projects(id),
            name TEXT NOT NULL,
            version_number INTEGER NOT NULL DEFAULT 1,
            version_label TEXT NOT NULL,
            visibility_scope TEXT NOT NULL DEFAULT 'project',
            scope_revision INTEGER NOT NULL DEFAULT 0,
            series_kind TEXT NOT NULL DEFAULT 'catalog',
            owner_linkable_object_id {reference},
            object_series_key TEXT,
            object_specific_signal_id {reference},
            current_revision_id {reference},
            status TEXT NOT NULL DEFAULT 'draft',
            description TEXT NOT NULL DEFAULT '',
            data_kind TEXT,
            timezone TEXT,
            content_hash TEXT,
            archived_at TEXT,
            archived_by TEXT,
            archived_reason_code TEXT,
            archived_reason_text TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            created_by TEXT NOT NULL,
            updated_by TEXT NOT NULL,
            CHECK (version_number > 0),
            CHECK (visibility_scope IN ('project', 'global')),
            CHECK (series_kind IN ('catalog', 'object_specific')),
            CHECK (status IN ('draft', 'validated', 'archived')),
            CONSTRAINT time_series_set_kind_ck CHECK (
                (series_kind = 'catalog'
                 AND owner_linkable_object_id IS NULL
                 AND object_series_key IS NULL
                 AND object_specific_signal_id IS NULL)
                OR
                (series_kind = 'object_specific'
                 AND owner_linkable_object_id IS NOT NULL
                 AND object_series_key IS NOT NULL
                 AND object_specific_signal_id IS NOT NULL
                 AND visibility_scope = 'project'
                 AND version_number = 1
                 AND version_label = 'object'
                 AND name = object_series_key)
            ),
            CONSTRAINT time_series_set_kind_identity_uk UNIQUE (id, series_kind),
            CONSTRAINT time_series_set_owner_identity_uk
                UNIQUE (id, owner_linkable_object_id),
            CONSTRAINT time_series_set_project_identity_uk
                UNIQUE (id, owner_project_id),
            CONSTRAINT time_series_set_owner_object_fk
                FOREIGN KEY (owner_linkable_object_id, owner_project_id)
                REFERENCES {register}(id, project_id)
        )
        """
    )

    statements.append(
        f"""
        CREATE TABLE IF NOT EXISTS {table['time_series_signals']} (
            id {identity},
            time_series_set_id {reference} NOT NULL
                REFERENCES {table['time_series_sets']}(id),
            series_kind TEXT NOT NULL,
            series_key TEXT NOT NULL,
            display_name TEXT NOT NULL,
            description TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'active',
            created_at TEXT NOT NULL,
            created_by TEXT NOT NULL,
            archived_at TEXT,
            archived_by TEXT,
            CHECK (status IN ('active', 'archived')),
            UNIQUE (time_series_set_id, series_key),
            UNIQUE (id, time_series_set_id),
            UNIQUE (id, time_series_set_id, series_key),
            FOREIGN KEY (time_series_set_id, series_kind)
                REFERENCES {table['time_series_sets']}(id, series_kind)
        )
        """
    )

    statements.append(
        f"""
        CREATE TABLE IF NOT EXISTS {table['time_series_set_revisions']} (
            id {identity},
            time_series_set_id {reference} NOT NULL
                REFERENCES {table['time_series_sets']}(id),
            revision_number INTEGER NOT NULL,
            supersedes_revision_id {reference}
                REFERENCES {table['time_series_set_revisions']}(id),
            time_series_source_id {reference}
                REFERENCES {table['time_series_sources']}(id),
            data_class_id {reference} NOT NULL
                REFERENCES time_series_data_classes(id),
            timezone TEXT NOT NULL,
            timestamp_convention TEXT NOT NULL DEFAULT 'period_start',
            content_hash TEXT,
            legacy_content_hash TEXT,
            state TEXT NOT NULL DEFAULT 'building',
            validation_payload_json TEXT NOT NULL DEFAULT {empty_json},
            change_summary TEXT NOT NULL DEFAULT '',
            metadata_json TEXT NOT NULL DEFAULT {empty_json},
            created_at TEXT NOT NULL,
            created_by TEXT NOT NULL,
            CHECK (revision_number > 0),
            CHECK (state IN ('building', 'sealed', 'legacy_unmaterialized')),
            CONSTRAINT revision_hash_state_ck CHECK (
                (state = 'sealed' AND content_hash IS NOT NULL)
                OR (state <> 'sealed' AND content_hash IS NULL)
            ),
            UNIQUE (time_series_set_id, revision_number),
            UNIQUE (id, time_series_set_id),
            UNIQUE (id, time_series_set_id, content_hash)
        )
        """
    )

    statements.append(
        f"""
        CREATE TABLE IF NOT EXISTS {table['time_series_revision_signals']} (
            set_revision_id {reference} NOT NULL,
            signal_id {reference} NOT NULL,
            time_series_set_id {reference} NOT NULL,
            semantic_type_id {reference} NOT NULL
                REFERENCES time_series_semantic_types(id),
            unit_id {reference} NOT NULL REFERENCES measurement_units(id),
            data_class_id {reference} NOT NULL
                REFERENCES time_series_data_classes(id),
            signal_role TEXT NOT NULL,
            aggregation TEXT NOT NULL,
            ordinal INTEGER NOT NULL,
            metadata_json TEXT NOT NULL DEFAULT {empty_json},
            PRIMARY KEY (set_revision_id, signal_id),
            CHECK (signal_role IN ('input', 'output', 'metadata')),
            CHECK (ordinal >= 0),
            FOREIGN KEY (set_revision_id, time_series_set_id)
                REFERENCES {table['time_series_set_revisions']}
                (id, time_series_set_id),
            FOREIGN KEY (signal_id, time_series_set_id)
                REFERENCES {table['time_series_signals']}(id, time_series_set_id),
            UNIQUE (set_revision_id, ordinal)
        )
        """
    )

    statements.append(
        f"""
        CREATE TABLE IF NOT EXISTS {table['time_series_periods']} (
            id {identity},
            set_revision_id {reference} NOT NULL
                REFERENCES {table['time_series_set_revisions']}(id),
            period_index INTEGER NOT NULL,
            timestamp_start TEXT NOT NULL,
            timestamp_end TEXT NOT NULL,
            duration_hours {double} NOT NULL,
            CHECK (duration_hours > 0),
            CHECK (timestamp_start < timestamp_end),
            CHECK (period_index >= 0),
            UNIQUE (set_revision_id, period_index),
            UNIQUE (set_revision_id, timestamp_start),
            UNIQUE (id, set_revision_id)
        )
        """
    )

    statements.append(
        f"""
        CREATE TABLE IF NOT EXISTS {table['time_series_values']} (
            set_revision_id {reference} NOT NULL,
            signal_id {reference} NOT NULL,
            time_series_period_id {reference} NOT NULL,
            value_numeric {double} NOT NULL,
            quality_flag TEXT,
            source_row_number INTEGER,
            metadata_json TEXT NOT NULL DEFAULT {empty_json},
            PRIMARY KEY (set_revision_id, signal_id, time_series_period_id),
            FOREIGN KEY (set_revision_id, signal_id)
                REFERENCES {table['time_series_revision_signals']}
                (set_revision_id, signal_id),
            FOREIGN KEY (time_series_period_id, set_revision_id)
                REFERENCES {table['time_series_periods']}(id, set_revision_id)
        )
        """
    )

    statements.append(
        f"""
        CREATE TABLE IF NOT EXISTS {table['time_series_revision_lineage']} (
            derived_set_revision_id {reference} NOT NULL,
            derived_signal_id {reference} NOT NULL,
            source_set_revision_id {reference} NOT NULL,
            source_signal_id {reference} NOT NULL,
            lineage_kind TEXT NOT NULL,
            source_content_hash TEXT NOT NULL,
            source_owner_linkable_object_id {reference},
            target_owner_linkable_object_id {reference},
            transformation_id {reference},
            created_at TEXT NOT NULL,
            created_by TEXT NOT NULL,
            reason_code TEXT NOT NULL,
            reason_text TEXT,
            PRIMARY KEY (
                derived_set_revision_id, derived_signal_id,
                source_set_revision_id, source_signal_id
            ),
            CHECK (lineage_kind IN (
                'object_specific_catalog_copy',
                'catalog_object_specific_copy',
                'allowlisted_transformation'
            )),
            FOREIGN KEY (derived_set_revision_id, derived_signal_id)
                REFERENCES {table['time_series_revision_signals']}
                (set_revision_id, signal_id),
            FOREIGN KEY (source_set_revision_id, source_signal_id)
                REFERENCES {table['time_series_revision_signals']}
                (set_revision_id, signal_id)
        )
        """
    )

    statements.extend(
        [
            f"""
            CREATE UNIQUE INDEX IF NOT EXISTS
                {_index_name('time_series_sets', 'catalog_version_number_uk')}
                ON {table['time_series_sets']}
                (owner_project_id, name, version_number)
                WHERE series_kind = 'catalog'
            """,
            f"""
            CREATE UNIQUE INDEX IF NOT EXISTS
                {_index_name('time_series_sets', 'catalog_version_label_uk')}
                ON {table['time_series_sets']}
                (owner_project_id, name, version_label)
                WHERE series_kind = 'catalog'
            """,
            f"""
            CREATE UNIQUE INDEX IF NOT EXISTS
                {_index_name('time_series_sets', 'object_series_key_uk')}
                ON {table['time_series_sets']}
                (owner_linkable_object_id, object_series_key)
                WHERE series_kind = 'object_specific'
            """,
            f"""
            CREATE INDEX IF NOT EXISTS
                {_index_name('time_series_sets', 'project_kind_status_idx')}
                ON {table['time_series_sets']}
                (owner_project_id, series_kind, status, updated_at DESC, id)
            """,
            f"""
            CREATE INDEX IF NOT EXISTS
                {_index_name('time_series_sets', 'owner_object_status_idx')}
                ON {table['time_series_sets']}
                (owner_linkable_object_id, status, updated_at DESC, id)
            """,
            f"""
            CREATE UNIQUE INDEX IF NOT EXISTS
                {_index_name('time_series_signals', 'object_single_signal_uk')}
                ON {table['time_series_signals']} (time_series_set_id)
                WHERE series_kind = 'object_specific'
            """,
            f"""
            CREATE INDEX IF NOT EXISTS
                {_index_name('time_series_set_revisions', 'set_state_number_idx')}
                ON {table['time_series_set_revisions']}
                (time_series_set_id, state, revision_number DESC, id DESC)
            """,
            f"""
            CREATE INDEX IF NOT EXISTS
                {_index_name('time_series_revision_signals', 'signal_revision_idx')}
                ON {table['time_series_revision_signals']}
                (signal_id, set_revision_id)
            """,
            f"""
            CREATE INDEX IF NOT EXISTS
                {_index_name('time_series_periods', 'revision_start_idx')}
                ON {table['time_series_periods']}
                (set_revision_id, timestamp_start, id)
            """,
            f"""
            CREATE INDEX IF NOT EXISTS
                {_index_name('time_series_values', 'revision_period_signal_idx')}
                ON {table['time_series_values']}
                (set_revision_id, time_series_period_id, signal_id)
            """,
        ]
    )
    return [statement.strip() for statement in statements]


def canonical_guard_script(backend: str) -> str:
    """Triggers that make the database the last defence (chapters 2.7, 9.6).

    Both engines refuse the same four things by the same stable name: touching a
    sealed revision or any of its children, making an unsealed revision current,
    redirecting a signal identity, and rewriting the lineage ledger.
    """

    table = canonical_table_names(backend)
    revisions = table["time_series_set_revisions"]
    children = (
        ("revision_signals", table["time_series_revision_signals"]),
        ("periods", table["time_series_periods"]),
        ("values", table["time_series_values"]),
    )

    if backend == "postgresql":
        statements = [
            f"""
            CREATE OR REPLACE FUNCTION {CANONICAL_SCHEMA_NAME}.reject_sealed_revision()
            RETURNS trigger AS $$
            BEGIN
                IF OLD.state = 'sealed' THEN
                    RAISE EXCEPTION 'TS_REVISION_SEALED';
                END IF;
                IF TG_OP = 'DELETE' THEN
                    RETURN OLD;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            f"""
            CREATE OR REPLACE FUNCTION
                {CANONICAL_SCHEMA_NAME}.reject_sealed_revision_child()
            RETURNS trigger AS $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM {revisions}
                    WHERE id = OLD.set_revision_id AND state = 'sealed'
                ) THEN
                    RAISE EXCEPTION 'TS_REVISION_SEALED';
                END IF;
                IF TG_OP = 'DELETE' THEN
                    RETURN OLD;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            f"""
            CREATE OR REPLACE FUNCTION
                {CANONICAL_SCHEMA_NAME}.reject_unsealed_current_revision()
            RETURNS trigger AS $$
            BEGIN
                IF NEW.current_revision_id IS NOT NULL AND NOT EXISTS (
                    SELECT 1 FROM {revisions}
                    WHERE id = NEW.current_revision_id
                      AND time_series_set_id = NEW.id
                      AND state = 'sealed'
                ) THEN
                    RAISE EXCEPTION 'TS_REVISION_NOT_SEALED';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            f"""
            CREATE OR REPLACE FUNCTION
                {CANONICAL_SCHEMA_NAME}.reject_signal_identity_change()
            RETURNS trigger AS $$
            BEGIN
                IF OLD.id IS DISTINCT FROM NEW.id
                   OR OLD.time_series_set_id IS DISTINCT FROM NEW.time_series_set_id
                   OR OLD.series_kind IS DISTINCT FROM NEW.series_kind
                   OR OLD.series_key IS DISTINCT FROM NEW.series_key THEN
                    RAISE EXCEPTION 'TS_SIGNAL_IDENTITY_IMMUTABLE';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            f"""
            CREATE OR REPLACE FUNCTION
                {CANONICAL_SCHEMA_NAME}.reject_lineage_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'TS_LEDGER_APPEND_ONLY';
            END;
            $$ LANGUAGE plpgsql;
            """,
            f"""
            DROP TRIGGER IF EXISTS ts_next_revision_sealed_update ON {revisions};
            CREATE TRIGGER ts_next_revision_sealed_update
            BEFORE UPDATE ON {revisions}
            FOR EACH ROW EXECUTE FUNCTION
                {CANONICAL_SCHEMA_NAME}.reject_sealed_revision();

            DROP TRIGGER IF EXISTS ts_next_revision_sealed_delete ON {revisions};
            CREATE TRIGGER ts_next_revision_sealed_delete
            BEFORE DELETE ON {revisions}
            FOR EACH ROW EXECUTE FUNCTION
                {CANONICAL_SCHEMA_NAME}.reject_sealed_revision();
            """,
        ]
        for label, child_table in children:
            statements.append(
                f"""
                DROP TRIGGER IF EXISTS ts_next_{label}_sealed_update ON {child_table};
                CREATE TRIGGER ts_next_{label}_sealed_update
                BEFORE UPDATE ON {child_table}
                FOR EACH ROW EXECUTE FUNCTION
                    {CANONICAL_SCHEMA_NAME}.reject_sealed_revision_child();

                DROP TRIGGER IF EXISTS ts_next_{label}_sealed_delete ON {child_table};
                CREATE TRIGGER ts_next_{label}_sealed_delete
                BEFORE DELETE ON {child_table}
                FOR EACH ROW EXECUTE FUNCTION
                    {CANONICAL_SCHEMA_NAME}.reject_sealed_revision_child();
                """
            )
        statements.append(
            f"""
            DROP TRIGGER IF EXISTS ts_next_set_current_revision_insert
                ON {table['time_series_sets']};
            CREATE TRIGGER ts_next_set_current_revision_insert
            BEFORE INSERT ON {table['time_series_sets']}
            FOR EACH ROW EXECUTE FUNCTION
                {CANONICAL_SCHEMA_NAME}.reject_unsealed_current_revision();

            DROP TRIGGER IF EXISTS ts_next_set_current_revision_update
                ON {table['time_series_sets']};
            CREATE TRIGGER ts_next_set_current_revision_update
            BEFORE UPDATE ON {table['time_series_sets']}
            FOR EACH ROW EXECUTE FUNCTION
                {CANONICAL_SCHEMA_NAME}.reject_unsealed_current_revision();

            DROP TRIGGER IF EXISTS ts_next_signal_identity_immutable
                ON {table['time_series_signals']};
            CREATE TRIGGER ts_next_signal_identity_immutable
            BEFORE UPDATE ON {table['time_series_signals']}
            FOR EACH ROW EXECUTE FUNCTION
                {CANONICAL_SCHEMA_NAME}.reject_signal_identity_change();

            DROP TRIGGER IF EXISTS ts_next_lineage_append_only_update
                ON {table['time_series_revision_lineage']};
            CREATE TRIGGER ts_next_lineage_append_only_update
            BEFORE UPDATE ON {table['time_series_revision_lineage']}
            FOR EACH ROW EXECUTE FUNCTION
                {CANONICAL_SCHEMA_NAME}.reject_lineage_mutation();

            DROP TRIGGER IF EXISTS ts_next_lineage_append_only_delete
                ON {table['time_series_revision_lineage']};
            CREATE TRIGGER ts_next_lineage_append_only_delete
            BEFORE DELETE ON {table['time_series_revision_lineage']}
            FOR EACH ROW EXECUTE FUNCTION
                {CANONICAL_SCHEMA_NAME}.reject_lineage_mutation();
            """
        )
        return "\n".join(statements)

    statements = [
        f"""
        DROP TRIGGER IF EXISTS ts_next_revision_sealed_update;
        CREATE TRIGGER ts_next_revision_sealed_update
        BEFORE UPDATE ON {revisions}
        FOR EACH ROW WHEN OLD.state = 'sealed'
        BEGIN
            SELECT RAISE(ABORT, 'TS_REVISION_SEALED');
        END;

        DROP TRIGGER IF EXISTS ts_next_revision_sealed_delete;
        CREATE TRIGGER ts_next_revision_sealed_delete
        BEFORE DELETE ON {revisions}
        FOR EACH ROW WHEN OLD.state = 'sealed'
        BEGIN
            SELECT RAISE(ABORT, 'TS_REVISION_SEALED');
        END;
        """
    ]
    for label, child_table in children:
        statements.append(
            f"""
            DROP TRIGGER IF EXISTS ts_next_{label}_sealed_update;
            CREATE TRIGGER ts_next_{label}_sealed_update
            BEFORE UPDATE ON {child_table}
            FOR EACH ROW WHEN EXISTS (
                SELECT 1 FROM {revisions}
                WHERE id = OLD.set_revision_id AND state = 'sealed'
            )
            BEGIN
                SELECT RAISE(ABORT, 'TS_REVISION_SEALED');
            END;

            DROP TRIGGER IF EXISTS ts_next_{label}_sealed_delete;
            CREATE TRIGGER ts_next_{label}_sealed_delete
            BEFORE DELETE ON {child_table}
            FOR EACH ROW WHEN EXISTS (
                SELECT 1 FROM {revisions}
                WHERE id = OLD.set_revision_id AND state = 'sealed'
            )
            BEGIN
                SELECT RAISE(ABORT, 'TS_REVISION_SEALED');
            END;
            """
        )
    statements.append(
        f"""
        DROP TRIGGER IF EXISTS ts_next_set_current_revision_insert;
        CREATE TRIGGER ts_next_set_current_revision_insert
        BEFORE INSERT ON {table['time_series_sets']}
        FOR EACH ROW WHEN NEW.current_revision_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM {revisions}
            WHERE id = NEW.current_revision_id
              AND time_series_set_id = NEW.id
              AND state = 'sealed'
        )
        BEGIN
            SELECT RAISE(ABORT, 'TS_REVISION_NOT_SEALED');
        END;

        DROP TRIGGER IF EXISTS ts_next_set_current_revision_update;
        CREATE TRIGGER ts_next_set_current_revision_update
        BEFORE UPDATE ON {table['time_series_sets']}
        FOR EACH ROW WHEN NEW.current_revision_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM {revisions}
            WHERE id = NEW.current_revision_id
              AND time_series_set_id = NEW.id
              AND state = 'sealed'
        )
        BEGIN
            SELECT RAISE(ABORT, 'TS_REVISION_NOT_SEALED');
        END;

        DROP TRIGGER IF EXISTS ts_next_signal_identity_immutable;
        CREATE TRIGGER ts_next_signal_identity_immutable
        BEFORE UPDATE ON {table['time_series_signals']}
        FOR EACH ROW WHEN OLD.id IS NOT NEW.id
            OR OLD.time_series_set_id IS NOT NEW.time_series_set_id
            OR OLD.series_kind IS NOT NEW.series_kind
            OR OLD.series_key IS NOT NEW.series_key
        BEGIN
            SELECT RAISE(ABORT, 'TS_SIGNAL_IDENTITY_IMMUTABLE');
        END;

        DROP TRIGGER IF EXISTS ts_next_lineage_append_only_update;
        CREATE TRIGGER ts_next_lineage_append_only_update
        BEFORE UPDATE ON {table['time_series_revision_lineage']}
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'TS_LEDGER_APPEND_ONLY');
        END;

        DROP TRIGGER IF EXISTS ts_next_lineage_append_only_delete;
        CREATE TRIGGER ts_next_lineage_append_only_delete
        BEFORE DELETE ON {table['time_series_revision_lineage']}
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'TS_LEDGER_APPEND_ONLY');
        END;
        """
    )
    return "\n".join(statements)


CANONICAL_ERROR_CATALOG = {
    "TS_INGEST_SIGNAL_SET_INCOMPLETE": (
        "timeseries.ingestion.signal_set_incomplete",
        "signals",
        "La revision no describe el conjunto completo de senales.",
    ),
    "TS_INGEST_PERIOD_CONFLICT": (
        "timeseries.ingestion.period_conflict",
        "periods",
        "Los periodos estan desordenados, duplicados o solapados.",
    ),
    "TS_INGEST_DURATION_INVALID": (
        "timeseries.ingestion.duration_invalid",
        "duration_hours",
        "La duracion del periodo no es positiva o no es coherente.",
    ),
    "TS_INGEST_VALUE_INVALID": (
        "timeseries.ingestion.value_invalid",
        "value",
        "Un valor esta ausente, duplicado o no es finito.",
    ),
    "TS_INGEST_TEMPORAL_CONTRACT_INVALID": (
        "timeseries.ingestion.temporal_contract_invalid",
        "periods",
        "La cobertura temporal esta fuera del contrato.",
    ),
    "TS_OBJECT_SERIES_KEY_CONFLICT": (
        "timeseries.ingestion.series_key_conflict",
        "series_key",
        "La clave de serie ya fue usada, incluso archivada.",
    ),
    "TS_REVISION_VALUE_COUNT_MISMATCH": (
        "timeseries.revision.value_count_mismatch",
        "values",
        "La fotografia no cubre exactamente senales por periodos.",
    ),
    "TS_REVISION_SEALED": (
        "timeseries.revision.sealed",
        "set_revision_id",
        "Una revision sellada y sus hijos no admiten cambios.",
    ),
    "TS_REVISION_NOT_SEALED": (
        "timeseries.revision.not_sealed",
        "current_revision_id",
        "Solo una revision sellada puede ser vigente.",
    ),
    "TS_SIGNAL_IDENTITY_IMMUTABLE": (
        "timeseries.signal.identity_immutable",
        "signal_id",
        "La identidad de una senal no se reasigna.",
    ),
    "TS_LEDGER_APPEND_ONLY": (
        "timeseries.ledger.append_only",
        "lineage",
        "El linaje solo admite INSERT.",
    ),
    "TS_SET_NOT_FOUND": (
        "timeseries.set.not_found",
        "set_id",
        "El set canonico no existe.",
    ),
}


class CanonicalRevisionError(RuntimeError):
    """A refusal from the canonical content model, carrying a stable code."""

    def __init__(self, code: str, **context):
        message_key, field, message = CANONICAL_ERROR_CATALOG[code]
        self.code = code
        self.message_key = message_key
        self.message = message
        self.field = field
        self.context = context
        super().__init__(f"{code}: {context}" if context else code)

    def as_problem(self) -> dict[str, object]:
        return {
            "code": self.code,
            "message_key": self.message_key,
            "message": self.message,
            "field": self.field,
            "context": dict(self.context),
        }


# Stable failure names raised by the portable database guards. The application
# produces friendly errors, but the database is the last defence (chapter 9.6).
DATABASE_GUARD_CODES = (
    "TS_REVISION_SEALED",
    "TS_REVISION_NOT_SEALED",
    "TS_SIGNAL_IDENTITY_IMMUTABLE",
    "TS_LEDGER_APPEND_ONLY",
)


def format_canonical_number(value: float) -> str:
    """Shortest round-trip decimal form, identical on both engines."""

    return repr(float(value))


class CanonicalContentHash:
    """Streaming canonical hash over ``ordinal, period_index`` (chapter 2.7).

    The digest covers only the content contract - never the set identity, its
    name or the revision number - so two identical contents hash equal on both
    engines and across different sets.
    """

    UNIT = "\x1f"

    def __init__(
        self,
        *,
        timezone: str,
        timestamp_convention: str,
        data_class_key: str,
    ):
        self._digest = hashlib.sha256()
        self._signal_count = 0
        self._period_count = 0
        self._value_count = 0
        self._write("canonical", str(CANONICAL_CONTENT_MODEL_VERSION))
        self._write("header", timezone, timestamp_convention, data_class_key)

    def _write(self, *fields: str) -> None:
        self._digest.update((self.UNIT.join(fields) + "\n").encode("utf-8"))

    def add_signal(
        self,
        *,
        ordinal: int,
        series_key: str,
        semantic_type_key: str,
        unit_key: str,
        data_class_key: str,
        signal_role: str,
        aggregation: str,
    ) -> None:
        self._write(
            "signal",
            str(ordinal),
            series_key,
            semantic_type_key,
            unit_key,
            data_class_key,
            signal_role,
            aggregation,
        )
        self._signal_count += 1

    def add_period(
        self,
        *,
        period_index: int,
        timestamp_start: str,
        timestamp_end: str,
        duration_hours: float,
    ) -> None:
        self._write(
            "period",
            str(period_index),
            timestamp_start,
            timestamp_end,
            format_canonical_number(duration_hours),
        )
        self._period_count += 1

    def add_value(self, *, ordinal: int, period_index: int, value: float) -> None:
        self._write(
            "value",
            str(ordinal),
            str(period_index),
            format_canonical_number(value),
        )
        self._value_count += 1

    @property
    def counts(self) -> tuple[int, int, int]:
        return self._signal_count, self._period_count, self._value_count

    def seal(self) -> str:
        self._write(
            "counts",
            str(self._signal_count),
            str(self._period_count),
            str(self._value_count),
        )
        return self._digest.hexdigest()


def normalize_canonical_signals(signals) -> list[dict]:
    """Validate the declared signal contract and freeze its ordinals."""

    normalized: list[dict] = []
    seen: set[str] = set()
    for ordinal, signal in enumerate(signals):
        series_key = str(signal.get("series_key") or "").strip()
        if not series_key:
            raise CanonicalRevisionError(
                "TS_INGEST_SIGNAL_SET_INCOMPLETE",
                ordinal=ordinal,
                reason="missing_series_key",
            )
        if series_key in seen:
            raise CanonicalRevisionError(
                "TS_INGEST_SIGNAL_SET_INCOMPLETE",
                series_key=series_key,
                reason="duplicated_series_key",
            )
        seen.add(series_key)
        signal_role = str(signal.get("signal_role") or "input")
        if signal_role not in ("input", "output", "metadata"):
            raise CanonicalRevisionError(
                "TS_INGEST_SIGNAL_SET_INCOMPLETE",
                series_key=series_key,
                signal_role=signal_role,
                reason="unknown_signal_role",
            )
        normalized.append(
            {
                "ordinal": ordinal,
                "series_key": series_key,
                "display_name": str(signal.get("display_name") or series_key),
                "description": str(signal.get("description") or ""),
                "semantic_type_key": str(signal.get("semantic_type_key") or ""),
                "unit_key": str(signal.get("unit_key") or ""),
                "data_class_key": signal.get("data_class_key"),
                "signal_role": signal_role,
                "aggregation": signal.get("aggregation"),
                "metadata": signal.get("metadata") or {},
            }
        )
    if not normalized:
        raise CanonicalRevisionError(
            "TS_INGEST_SIGNAL_SET_INCOMPLETE", reason="no_signals"
        )
    return normalized


def normalize_canonical_periods(periods) -> list[dict]:
    """Validate ordered, non-overlapping coverage before anything is written."""

    normalized: list[dict] = []
    for position, period in enumerate(periods):
        declared_index = period.get("period_index")
        period_index = position if declared_index is None else int(declared_index)
        timestamp_start = str(period.get("timestamp_start") or "")
        timestamp_end = str(period.get("timestamp_end") or "")
        if not timestamp_start or not timestamp_end:
            raise CanonicalRevisionError(
                "TS_INGEST_PERIOD_CONFLICT",
                period_index=period_index,
                reason="missing_timestamp",
            )
        duration_hours = period.get("duration_hours")
        if duration_hours is None:
            raise CanonicalRevisionError(
                "TS_INGEST_DURATION_INVALID",
                period_index=period_index,
                reason="missing_duration",
            )
        duration_hours = float(duration_hours)
        if not duration_hours > 0:
            raise CanonicalRevisionError(
                "TS_INGEST_DURATION_INVALID",
                period_index=period_index,
                duration_hours=duration_hours,
            )
        if timestamp_end <= timestamp_start:
            raise CanonicalRevisionError(
                "TS_INGEST_DURATION_INVALID",
                period_index=period_index,
                reason="end_before_start",
            )
        normalized.append(
            {
                "period_index": period_index,
                "timestamp_start": timestamp_start,
                "timestamp_end": timestamp_end,
                "duration_hours": duration_hours,
            }
        )
    if not normalized:
        raise CanonicalRevisionError(
            "TS_INGEST_TEMPORAL_CONTRACT_INVALID", reason="no_periods"
        )
    for position, period in enumerate(normalized):
        if period["period_index"] != position:
            raise CanonicalRevisionError(
                "TS_INGEST_PERIOD_CONFLICT",
                period_index=period["period_index"],
                expected_period_index=position,
                reason="coverage_not_ordered",
            )
        if position == 0:
            continue
        previous = normalized[position - 1]
        if period["timestamp_start"] < previous["timestamp_end"]:
            raise CanonicalRevisionError(
                "TS_INGEST_PERIOD_CONFLICT",
                period_index=period["period_index"],
                reason="periods_overlap",
            )
        if period["timestamp_start"] <= previous["timestamp_start"]:
            raise CanonicalRevisionError(
                "TS_INGEST_PERIOD_CONFLICT",
                period_index=period["period_index"],
                reason="coverage_not_ordered",
            )
    return normalized


def canonical_value_records(values):
    """Yield ``(series_key, period_index, value, quality_flag, row_number)``.

    A mapping is read as one dense column per series; any other iterable is
    consumed lazily, so a publication whose source dies halfway really dies
    halfway and must roll back (AC-ESP-10).
    """

    if hasattr(values, "items"):
        for series_key, series_values in values.items():
            for period_index, value in enumerate(series_values):
                yield str(series_key), period_index, value, None, None
        return
    for record in values:
        yield (
            str(record.get("series_key") or ""),
            record.get("period_index"),
            record.get("value"),
            record.get("quality_flag"),
            record.get("source_row_number"),
        )
