"""Transactional catalog projection for TS7-005 (chapters 9.3, 9.5, 9.7).

``time_series_catalog_entries`` is the only table a global catalog list reads.
It holds one row per signal of a ``catalog`` set, derived from the set's
``current_revision_id``, and it is maintained inside the same transaction that
seals a revision - never by a background job that can drift.

The table lands in the same physical space as the rest of the TS-7 expansion:
schema ``ts_next`` on PostgreSQL and a ``_next`` suffix on SQLite.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import time
import unicodedata

from app.time_series_canonical import canonical_space_table_name


CATALOG_SECTION_INPUTS = "inputs"

PUBLISH_OPERATION_KIND = "publish_set_revision"

# Chapter 9.7 retains a completed idempotency record for at least a day.
IDEMPOTENCY_RETENTION_HOURS = 24

# A reserved record older than its lease belonged to an attempt that died
# before commit, so a retry may take it over.
IDEMPOTENCY_LEASE_SECONDS = 300

CATALOG_PROJECTION_LOGICAL_TABLES = (
    "time_series_catalog_entries",
    "time_series_catalog_generations",
    "time_series_operation_idempotency",
)


def catalog_projection_table_names(backend: str) -> dict[str, str]:
    """Physical name of every TS7-005 table for one database engine."""

    return {
        logical: canonical_space_table_name(logical, backend)
        for logical in CATALOG_PROJECTION_LOGICAL_TABLES
    }


def catalog_projection_schema_statements(backend: str) -> list[str]:
    """Additive DDL for the projection, its generation counter and idempotency."""

    postgres = backend == "postgresql"
    table = catalog_projection_table_names(backend)
    canonical = {
        logical: canonical_space_table_name(logical, backend)
        for logical in (
            "time_series_sets",
            "time_series_signals",
            "time_series_set_revisions",
        )
    }
    identity = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if postgres
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    reference = "BIGINT" if postgres else "INTEGER"
    double = "DOUBLE PRECISION" if postgres else "REAL"

    statements = [
        f"""
        CREATE TABLE IF NOT EXISTS {table['time_series_catalog_entries']} (
            signal_id {reference} PRIMARY KEY,
            time_series_set_id {reference} NOT NULL,
            series_kind TEXT NOT NULL DEFAULT 'catalog',
            owner_project_id {reference} NOT NULL REFERENCES projects(id),
            owner_project_name TEXT NOT NULL,
            owner_project_name_sort TEXT NOT NULL,
            set_name TEXT NOT NULL,
            set_version_number INTEGER NOT NULL,
            set_version_label TEXT NOT NULL,
            set_description TEXT NOT NULL DEFAULT '',
            visibility_scope TEXT NOT NULL,
            set_status TEXT NOT NULL,
            signal_status TEXT NOT NULL,
            series_key TEXT NOT NULL,
            display_name TEXT NOT NULL,
            signal_description TEXT NOT NULL DEFAULT '',
            display_name_sort TEXT NOT NULL,
            search_text_normalized TEXT NOT NULL,
            semantic_type_id {reference} NOT NULL
                REFERENCES time_series_semantic_types(id),
            semantic_type_key TEXT NOT NULL,
            data_class_id {reference} NOT NULL
                REFERENCES time_series_data_classes(id),
            data_class_key TEXT NOT NULL,
            unit_id {reference} NOT NULL REFERENCES measurement_units(id),
            unit_key TEXT NOT NULL,
            source_kind TEXT NOT NULL,
            current_revision_id {reference} NOT NULL,
            revision_number INTEGER NOT NULL,
            revision_created_at TEXT NOT NULL,
            source_timezone TEXT NOT NULL,
            coverage_start TEXT NOT NULL,
            coverage_end TEXT NOT NULL,
            period_count INTEGER NOT NULL,
            value_count INTEGER NOT NULL,
            nominal_resolution_seconds {double} NOT NULL,
            min_resolution_seconds {double} NOT NULL,
            max_resolution_seconds {double} NOT NULL,
            regularity TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            association_count INTEGER NOT NULL DEFAULT 0,
            binding_count INTEGER NOT NULL DEFAULT 0,
            projection_revision INTEGER NOT NULL DEFAULT 1,
            CONSTRAINT ts7_catalog_entry_kind_ck CHECK (series_kind = 'catalog'),
            CHECK (visibility_scope IN ('project', 'global')),
            CHECK (set_status IN ('draft', 'validated', 'archived')),
            CHECK (signal_status IN ('active', 'archived')),
            CHECK (regularity IN ('regular', 'irregular')),
            CHECK (period_count > 0),
            CHECK (value_count >= period_count),
            CHECK (revision_number > 0),
            CHECK (projection_revision > 0),
            CHECK (association_count >= 0),
            CHECK (binding_count >= 0),
            CHECK (min_resolution_seconds > 0),
            CHECK (nominal_resolution_seconds >= min_resolution_seconds),
            CHECK (max_resolution_seconds >= nominal_resolution_seconds),
            CHECK (coverage_start < coverage_end),
            FOREIGN KEY (signal_id, time_series_set_id)
                REFERENCES {canonical['time_series_signals']}
                (id, time_series_set_id),
            FOREIGN KEY (time_series_set_id, series_kind)
                REFERENCES {canonical['time_series_sets']}(id, series_kind),
            FOREIGN KEY (current_revision_id, time_series_set_id)
                REFERENCES {canonical['time_series_set_revisions']}
                (id, time_series_set_id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS {table['time_series_catalog_generations']} (
            section TEXT PRIMARY KEY,
            generation {reference} NOT NULL CHECK (generation >= 0),
            updated_at TEXT NOT NULL
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS {table['time_series_operation_idempotency']} (
            id {identity},
            actor_id TEXT NOT NULL,
            operation_kind TEXT NOT NULL,
            scope_key TEXT NOT NULL,
            idempotency_key TEXT NOT NULL,
            request_hash TEXT NOT NULL,
            state TEXT NOT NULL,
            lease_owner TEXT,
            lease_expires_at TEXT,
            http_status INTEGER,
            response_json TEXT NOT NULL DEFAULT '{{}}',
            resource_refs_json TEXT NOT NULL DEFAULT '{{}}',
            created_at TEXT NOT NULL,
            completed_at TEXT,
            expires_at TEXT NOT NULL,
            CHECK (state IN ('reserved', 'completed', 'failed')),
            CONSTRAINT ts7_idempotency_completion_ck CHECK (
                (state = 'reserved' AND completed_at IS NULL)
                OR (state <> 'reserved' AND completed_at IS NOT NULL)
            ),
            UNIQUE (actor_id, operation_kind, scope_key, idempotency_key)
        )
        """,
    ]

    entries = table["time_series_catalog_entries"]
    prefix = "time_series_catalog_entries_next"
    # One index per documented query shape (chapter 9.5). Every list order ends
    # in ``signal_id``, so each index carries it as its last column and the
    # keyset ladder never falls back to a sort.
    for suffix, columns in (
        ("updated_at_idx", "updated_at DESC, display_name_sort, signal_id"),
        ("display_name_idx", "display_name_sort, signal_id"),
        ("owner_project_idx", "owner_project_name_sort, signal_id"),
        ("semantic_type_idx", "semantic_type_key, signal_id"),
        ("coverage_start_idx", "coverage_start, signal_id"),
        ("coverage_end_idx", "coverage_end, signal_id"),
        ("resolution_idx", "nominal_resolution_seconds, signal_id"),
        ("association_count_idx", "association_count, signal_id"),
        ("binding_count_idx", "binding_count, signal_id"),
        (
            "visibility_idx",
            "visibility_scope, owner_project_id, set_status, signal_status, "
            "updated_at DESC, signal_id",
        ),
        ("set_idx", "time_series_set_id, signal_id"),
    ):
        statements.append(
            f"""
            CREATE INDEX IF NOT EXISTS {prefix}_{suffix}
            ON {entries} ({columns})
            """
        )

    if postgres:
        # Full-text search is served by a stored vector so the list never has
        # to compute it per row; SQLite indexes the normalized text directly.
        statements.append(
            f"""
            ALTER TABLE {entries}
            ADD COLUMN IF NOT EXISTS search_vector tsvector
            GENERATED ALWAYS AS (
                to_tsvector('simple', search_text_normalized)
            ) STORED
            """
        )
        statements.append(
            f"""
            CREATE INDEX IF NOT EXISTS {prefix}_search_gin
            ON {entries} USING GIN (search_vector)
            """
        )
    else:
        statements.append(
            f"""
            CREATE INDEX IF NOT EXISTS {prefix}_search_idx
            ON {entries} (search_text_normalized, signal_id)
            """
        )

    statements.append(
        f"""
        CREATE INDEX IF NOT EXISTS
            time_series_operation_idempotency_next_expiry_idx
        ON {table['time_series_operation_idempotency']} (state, expires_at)
        """
    )
    return [statement.strip() for statement in statements]


def normalize_sort_text(value: str) -> str:
    """Stable sort key: NFKD, folded accents, lowercase, collapsed whitespace.

    Chapter 9.4 forbids depending on the server collation, so every string used
    to filter or order carries a normalized column computed here.
    """

    decomposed = unicodedata.normalize("NFKD", str(value or ""))
    without_accents = "".join(
        character
        for character in decomposed
        if not unicodedata.combining(character)
    )
    return " ".join(without_accents.casefold().split())


def normalize_search_text(*parts: str) -> str:
    """Searchable text: normalized terms, deduplicated, order preserved.

    Technical identifiers stay whole terms so `series_key` remains searchable.
    """

    terms: list[str] = []
    seen: set[str] = set()
    for part in parts:
        for term in normalize_sort_text(part).split():
            if term not in seen:
                seen.add(term)
                terms.append(term)
    return " ".join(terms)


def summarize_coverage(
    *,
    coverage_start: str,
    coverage_end: str,
    period_count: int,
    duration_histogram: dict[float, int],
) -> dict[str, object]:
    """Coverage and resolution facts of a revision, from its period durations.

    The histogram has one entry per distinct duration, so a regular series
    summarizes from a single row instead of walking every period.
    """

    if period_count <= 0 or not duration_histogram:
        raise ValueError("a projected revision covers at least one period")
    durations = sorted(duration_histogram)
    nominal = min(
        durations,
        key=lambda duration: (-duration_histogram[duration], duration),
    )
    return {
        "coverage_start": coverage_start,
        "coverage_end": coverage_end,
        "period_count": int(period_count),
        "nominal_resolution_seconds": float(nominal) * 3600.0,
        "min_resolution_seconds": float(durations[0]) * 3600.0,
        "max_resolution_seconds": float(durations[-1]) * 3600.0,
        "regularity": "regular" if len(durations) == 1 else "irregular",
    }


def publish_scope_key(*, project_id: int, set_id: int | None, name: str) -> str:
    """Target of a publication, stable across retries of the same request."""

    if set_id is not None:
        return f"project:{project_id}/set:{set_id}"
    return f"project:{project_id}/name:{name}"


def idempotency_request_hash(payload: dict[str, object]) -> str:
    """Canonical digest of a request, used to refuse a reused key.

    The digest covers the target, the declared contract and the temporal
    coverage - everything a retry must repeat to be the same request.
    """

    canonical = json.dumps(
        payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def publish_request_payload(
    *,
    project_id: int,
    set_id: int | None,
    name: str,
    data_class_key: str,
    timezone_name: str,
    timestamp_convention: str,
    signals: list[dict],
    periods: list[dict],
    request_fingerprint: str | None = None,
) -> dict[str, object]:
    """Canonical view of a publication request for its idempotency hash.

    Values are consumed as a stream, so the store cannot digest them twice.
    The caller - which holds the request body, the uploaded file checksum or
    the staged ingestion id - passes their fingerprint here, and two different
    bodies under one key then conflict instead of replaying.
    """

    return {
        "request_fingerprint": request_fingerprint,
        "project_id": int(project_id),
        "set_id": None if set_id is None else int(set_id),
        "name": name,
        "data_class_key": data_class_key,
        "timezone": timezone_name,
        "timestamp_convention": timestamp_convention,
        "signals": [
            [
                signal["ordinal"],
                signal["series_key"],
                signal["semantic_type_key"],
                signal["unit_key"],
                signal["data_class_key"],
                signal["signal_role"],
                signal["aggregation"],
            ]
            for signal in signals
        ],
        "periods": [
            [
                period["period_index"],
                period["timestamp_start"],
                period["timestamp_end"],
                period["duration_hours"],
            ]
            for period in periods
        ],
    }


# Every documented order translates to a total tuple that ends in ``signal_id``
# (chapter 9.4). All projection columns are NOT NULL, so the explicit null flag
# the chapter requires for nullable keys has no key to guard here.
CATALOG_ORDER_COLUMNS = {
    "updated_at": "updated_at",
    "display_name": "display_name_sort",
    "owner_project_name": "owner_project_name_sort",
    "semantic_type": "semantic_type_key",
    "coverage_start": "coverage_start",
    "coverage_end": "coverage_end",
    "nominal_resolution_seconds": "nominal_resolution_seconds",
    "association_count": "association_count",
    "binding_count": "binding_count",
}

# Every column the projection derives from the canonical model. ``series_kind``
# is the constant discriminator and ``projection_revision`` counts rewrites, so
# neither is derived and neither takes part in the convergence hash.
CATALOG_ENTRY_COLUMNS = (
    "signal_id",
    "time_series_set_id",
    "owner_project_id",
    "owner_project_name",
    "owner_project_name_sort",
    "set_name",
    "set_version_number",
    "set_version_label",
    "set_description",
    "visibility_scope",
    "set_status",
    "signal_status",
    "series_key",
    "display_name",
    "signal_description",
    "display_name_sort",
    "search_text_normalized",
    "semantic_type_id",
    "semantic_type_key",
    "data_class_id",
    "data_class_key",
    "unit_id",
    "unit_key",
    "source_kind",
    "current_revision_id",
    "revision_number",
    "revision_created_at",
    "source_timezone",
    "coverage_start",
    "coverage_end",
    "period_count",
    "value_count",
    "nominal_resolution_seconds",
    "min_resolution_seconds",
    "max_resolution_seconds",
    "regularity",
    "updated_at",
    "association_count",
    "binding_count",
)


def catalog_projection_content_hash(rows) -> str:
    """Digest of the projected rows, used to compare a rebuild to the live table."""

    digest = hashlib.sha256()
    for row in rows:
        digest.update(
            "\x1f".join(str(row[column]) for column in CATALOG_ENTRY_COLUMNS).encode(
                "utf-8"
            )
        )
        digest.update(b"\n")
    return digest.hexdigest()


DEFAULT_CATALOG_ORDER = "-updated_at,display_name"

CATALOG_PAGE_DEFAULT_LIMIT = 50
CATALOG_PAGE_MAX_LIMIT = 200

CURSOR_LIFETIME_SECONDS = 15 * 60


class CatalogQueryError(RuntimeError):
    """A refusal from the catalog read model, carrying a stable code."""

    def __init__(self, code: str, **context):
        self.code = code
        self.context = context
        super().__init__(f"{code}: {context}" if context else code)


def parse_catalog_order(order: str | None) -> list[tuple[str, bool]]:
    """Translate an order expression into a total, deterministic key tuple."""

    expression = (order or DEFAULT_CATALOG_ORDER).strip()
    terms: list[tuple[str, bool]] = []
    seen: set[str] = set()
    for raw_term in expression.split(","):
        term = raw_term.strip()
        if not term:
            continue
        descending = term.startswith("-")
        name = term.lstrip("-+").strip()
        if name not in CATALOG_ORDER_COLUMNS:
            raise CatalogQueryError("TS_QUERY_ORDER_UNSUPPORTED", order=name)
        column = CATALOG_ORDER_COLUMNS[name]
        if column in seen:
            continue
        seen.add(column)
        terms.append((column, descending))
    terms.append(("signal_id", False))
    return terms


def normalize_catalog_order(order: str | None) -> str:
    """Canonical spelling of an order, so a cursor can be compared to it."""

    reverse = {column: name for name, column in CATALOG_ORDER_COLUMNS.items()}
    return ",".join(
        f"{'-' if descending else ''}{reverse[column]}"
        for column, descending in parse_catalog_order(order)
        if column in reverse
    )


def normalize_catalog_limit(limit: int | None) -> int:
    if limit is None:
        return CATALOG_PAGE_DEFAULT_LIMIT
    limit = int(limit)
    if limit < 1 or limit > CATALOG_PAGE_MAX_LIMIT:
        raise CatalogQueryError(
            "TS_QUERY_LIMIT_INVALID", limit=limit, maximum=CATALOG_PAGE_MAX_LIMIT
        )
    return limit


def catalog_page_sql(
    *,
    entries_table: str,
    order_terms: list[tuple[str, bool]],
    cursor_key: list | None,
    limit: int,
    filter_sql: str = "",
    filter_parameters: tuple = (),
) -> tuple[str, tuple]:
    """Keyset page over the projection, as a ladder of comparisons.

    ``OFFSET`` is never used, and the ladder never assumes both engines treat
    equality the same way; it only compares columns that are NOT NULL.
    """

    order_sql = ", ".join(
        f"{column} {'DESC' if descending else 'ASC'}"
        for column, descending in order_terms
    )
    parameters: list = list(filter_parameters)
    conditions: list[str] = []
    if filter_sql:
        conditions.append(f"({filter_sql})")
    if cursor_key is not None:
        if len(cursor_key) != len(order_terms):
            raise CatalogQueryError("TS_QUERY_CURSOR_MISMATCH", reason="key_arity")
        # The leading column also carries a non strict bound. It is redundant
        # with the ladder, but it is what lets the index start at the cursor
        # instead of at the top: without it the engine scans from the first row
        # and filters, and a keyset page degrades into an offset page.
        leading_column, leading_descending = order_terms[0]
        bound = f"{leading_column} {'<=' if leading_descending else '>='} ?"
        parameters.append(cursor_key[0])
        rungs = []
        for index, (column, descending) in enumerate(order_terms):
            comparison = "<" if descending else ">"
            equalities = " AND ".join(
                f"{order_terms[before][0]} = ?" for before in range(index)
            )
            rung = f"{column} {comparison} ?"
            if equalities:
                rung = f"{equalities} AND {rung}"
            rungs.append(f"({rung})")
            parameters.extend(cursor_key[:index])
            parameters.append(cursor_key[index])
        conditions.append(f"{bound} AND ({' OR '.join(rungs)})")
    where = f"WHERE {' AND '.join(conditions)}" if conditions else ""
    # One extra row answers ``has_more`` without a second count.
    parameters.append(limit + 1)
    return (
        f"SELECT entry.* FROM {entries_table} AS entry {where} "
        f"ORDER BY {order_sql} LIMIT ?",
        tuple(parameters),
    )



def object_context_page_sql(
    *,
    entries_table: str,
    associations_table: str,
    sets_table: str,
    signals_table: str,
    linkable_object_id: int,
    cursor_key: list | None,
    limit: int,
) -> tuple[str, tuple]:
    """Contextual list of one object as the ``UNION ALL`` of chapter 9.5.

    The catalog arm walks the object's active associations into the projection;
    the local arm walks the sets the object owns. Each arm keeps its own
    discriminator, they cannot overlap, and the keyset applies to the union - a
    local series is never found by looking its ID up in the global projection.

    Both arms carry the keyset and their own bound, so the union materializes at
    most two pages before its final ordering instead of every row an object can
    reach.
    """

    ordering = "ORDER BY updated_at DESC, signal_id ASC"

    def arm_keyset(updated_at_column: str, signal_id_column: str) -> str:
        if cursor_key is None:
            return ""
        # The non strict bound on the leading column is what lets each arm seek
        # instead of scanning from its first row.
        return (
            f"AND {updated_at_column} <= ? "
            f"AND (({updated_at_column} < ?) "
            f"OR ({updated_at_column} = ? AND {signal_id_column} > ?))"
        )

    keyset_parameters: list = (
        []
        if cursor_key is None
        else [cursor_key[0], cursor_key[0], cursor_key[0], cursor_key[1]]
    )

    catalog_arm = f"""
        SELECT * FROM (
            SELECT 'catalog' AS source, entry.signal_id AS signal_id,
                   entry.series_key AS series_key,
                   entry.display_name AS display_name,
                   entry.time_series_set_id AS time_series_set_id,
                   entry.semantic_type_key AS semantic_type_key,
                   entry.unit_key AS unit_key,
                   entry.updated_at AS updated_at,
                   association.binding_role_id AS binding_role_id
            FROM {associations_table} AS association
            JOIN {entries_table} AS entry
              ON entry.signal_id = association.signal_id
            WHERE association.linkable_object_id = ?
              AND association.status = 'active'
              {arm_keyset("entry.updated_at", "entry.signal_id")}
            {ordering}
            LIMIT ?
        ) AS catalog_arm
    """
    local_arm = f"""
        SELECT * FROM (
            SELECT 'object_specific' AS source,
                   signal.id AS signal_id,
                   signal.series_key AS series_key,
                   signal.display_name AS display_name,
                   the_set.id AS time_series_set_id,
                   -- Each arm is its own subquery, so an untyped NULL would
                   -- settle on a type before the union and stop matching.
                   CAST(NULL AS TEXT) AS semantic_type_key,
                   CAST(NULL AS TEXT) AS unit_key,
                   the_set.updated_at AS updated_at,
                   CAST(NULL AS BIGINT) AS binding_role_id
            FROM {sets_table} AS the_set
            JOIN {signals_table} AS signal
              ON signal.id = the_set.object_specific_signal_id
            WHERE the_set.owner_linkable_object_id = ?
              AND the_set.series_kind = 'object_specific'
              {arm_keyset("the_set.updated_at", "signal.id")}
            ORDER BY the_set.updated_at DESC, signal.id ASC
            LIMIT ?
        ) AS local_arm
    """
    parameters: list = [int(linkable_object_id), *keyset_parameters, limit + 1]
    parameters.extend([int(linkable_object_id), *keyset_parameters, limit + 1])
    parameters.append(limit + 1)
    sql = f"""
        SELECT * FROM (
            {catalog_arm}
            UNION ALL
            {local_arm}
        ) AS object_context
        {ordering}
        LIMIT ?
    """
    return sql, tuple(parameters)


def _b64(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def _unb64(encoded: str) -> bytes:
    padding = "=" * (-len(encoded) % 4)
    return base64.urlsafe_b64decode(encoded + padding)


def encode_catalog_cursor(payload: dict, secret: bytes) -> str:
    """Opaque, signed cursor bound to section, order, limit and generation."""

    body = json.dumps(
        payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False
    ).encode("utf-8")
    signature = hmac.new(secret, body, hashlib.sha256).digest()[:16]
    # Body and signature are encoded separately: a raw ``.`` inside the binary
    # signature would otherwise split the cursor in the wrong place.
    return f"{_b64(body)}.{_b64(signature)}"


def decode_catalog_cursor(
    cursor: str,
    secret: bytes,
    *,
    section: str,
    order: str,
    limit: int,
    generation: int,
    actor_class: str | None = None,
    filters_hash: str | None = None,
    now: float | None = None,
) -> list:
    """Return the keyset position, or refuse with a stable navigation code."""

    try:
        encoded_body, encoded_signature = cursor.split(".", 1)
        body = _unb64(encoded_body)
        signature = _unb64(encoded_signature)
        payload = json.loads(body.decode("utf-8"))
    except Exception as error:  # noqa: BLE001 - any malformed cursor is a mismatch
        raise CatalogQueryError(
            "TS_QUERY_CURSOR_MISMATCH", reason="unreadable"
        ) from error
    expected = hmac.new(secret, body, hashlib.sha256).digest()[:16]
    if not hmac.compare_digest(expected, signature):
        raise CatalogQueryError("TS_QUERY_CURSOR_MISMATCH", reason="signature")
    moment = time.time() if now is None else now
    if moment - float(payload.get("t", 0)) > CURSOR_LIFETIME_SECONDS:
        raise CatalogQueryError("TS_QUERY_CURSOR_EXPIRED")
    if (
        payload.get("s") != section
        or payload.get("o") != order
        or int(payload.get("l", -1)) != limit
        or (actor_class is not None and payload.get("a") != actor_class)
        or (filters_hash is not None and payload.get("f") != filters_hash)
    ):
        raise CatalogQueryError("TS_QUERY_CURSOR_MISMATCH", reason="query_changed")
    if int(payload.get("g", -1)) != generation:
        raise CatalogQueryError(
            "TS_QUERY_SNAPSHOT_CHANGED",
            cursor_generation=payload.get("g"),
            current_generation=generation,
        )
    return list(payload["k"])
